### ISSUE TITLE
How to train on custom datasets?

### ISSUE THREAD

**Issue by harsha-sharechat-account** [facebookresearch/dlrm#101]
can some one point out how we can train on custom datasets ?

**Comment by mnaumovfb** [comment]
The model accepts as input (i) a vector of floating point values corresponding to continuous features and (ii) a set of indices corresponding to categorical features, and produces as an output a probability of the associated event. If your dataset can be distilled into this input and output you can try interfacing it with DLRM. As an example, you can review the [existing interface](https://github.com/facebookresearch/dlrm/issues/58#issuecomment-590185652).

**Comment by harsha-sharechat-account** [comment]
lets say we want to build recommendation system of CTR on E- commerce , where we have 3 users (u1,u2,u3) and 4 items (i1,i2,i3,i4) and say these were the transactions
u1 clicked i1
u1 did not click i2
u2 clicked i3
u3 clicked i4
u3 did not click i2 even after looking at the item
 can you explain how do we encode for  X , LS_o and LS_i , T

**Comment by mnaumovfb** [comment]
You will have to find a way to transform your data into the model input. You will find a lot of scientific literature about this topic in [KDD](https://www.kdd.org/conferences). That's probably the best place to look for an answer to this type of question.
