### ISSUE TITLE
Data downloading link is not available

### ISSUE THREAD

**Issue by 2seungeun** [facebookresearch/dlrm#11]
It would be better if the link is updated to https://s3-eu-west-1.amazonaws.com/kaggle-display-advertising-challenge-dataset/dac.tar.gz

**Comment by mnaumovfb** [comment]
Thank you for pointing out an alternative link to the dataset. However, we have not used this link.

To the best of our knowledge, we provide a link to the official website of the Kaggle Display Advertising Challenge Dataset in the README.

**Comment by lucky096** [comment]
For clarity: the smaller version of the dataset is not available anymore (removed from kaggle), however the total data (i.e 7 days) is still available here : http://labs.criteo.com/2014/02/kaggle-display-advertising-challenge-dataset/

**Comment by mnaumovfb** [comment]
Ok, I think I see where the confusion comes from. I have adjusted the links.
