### ISSUE TITLE
When I use the GPU run/inference/recommendation, the program USES the CPU

### ISSUE THREAD

**Issue by lambozhang** [facebookresearch/dlrm#121]
I ran this code：
./run_local.sh pytorch dlrm terabyte gpu --max-in-range=10000000
I got this：
+ python3 python/main.py --profile dlrm-terabyte-pytorch --config ../mlperf.conf --model dlrm --model-path /root/mlperf/.5/recommendation/model/dlrm_terabyte.pytorch --dataset terabyte --dataset-path /root/mlperf/mlperf_inference/v0.5/recomeo --output /root/mlperf/mlperf_inference/v0.5/recommendation/output/pytorch-gpu/dlrm --use-gpu --max-ind-range=10000000
INFO:main:Namespace(accuracy=False, backend='pytorch-native', cache=0, config='../mlperf.conf', count_queries=None, couna_sub_sample_rate=0.0, dataset='terabyte', dataset_path='/root/mlperf/mlperf_inference/v0.5/recommendation/fake_criteo',d_peak_performance=False, inputs=['continuous and categorical features'], max_batchsize=2048, max_ind_range=10000000, ma_samples_to_aggregate=None, min_samples_to_aggregate=None, mlperf_bin_loader=False, model='dlrm', model_path='/root/mlpe/v0.5/recommendation/model/dlrm_terabyte.pytorch', numpy_rand_seed=123, output='/root/mlperf/mlperf_inference/v0.5/recomtorch-gpu/dlrm', outputs=['probability'], profile='dlrm-terabyte-pytorch', samples_per_query=None, samples_to_aggregate=gregate_quantile_file=None, samples_to_aggregate_trace_file='dlrm_trace_of_aggregated_samples.txt', scenario='SingleStree, test_num_workers=0, threads=8, use_gpu=True)
Using CPU...
Does anybody know why？

**Comment by mnaumovfb** [comment]
Just to clarify, this question is related to MLPerf Inference [DLRM with loadgen implementation](https://github.com/mlperf/inference/tree/master/v0.5/recommendation)

In MLPerf inference implementation the decision to use CPU or GPU happens [here](https://github.com/mlperf/inference/blob/master/v0.5/recommendation/python/backend_pytorch_native.py#L21). Please double check that your system (i) has GPUs, (ii) the driver is installed and has the correct version, and (iii) PyTorch is installed with GPU support and therefore call `torch.cuda.is_available()` returns True. 

Aside, from this recommendation notice that the commands for MLPerf inference benchmark are suggested in the README under Run Local section. I would try them first before experimenting with custom commands.

**Comment by lambozhang** [comment]
> Just to clarify, this question is related to MLPerf Inference [DLRM with loadgen implementation](https://github.com/mlperf/inference/tree/master/v0.5/recommendation)
> 
> In MLPerf inference implementation the decision to use CPU or GPU happens [here](https://github.com/mlperf/inference/blob/master/v0.5/recommendation/python/backend_pytorch_native.py#L21). Please double check that your system (i) has GPUs, (ii) the driver is installed and has the correct version, and (iii) PyTorch is installed with GPU support and therefore call `torch.cuda.is_available()` returns True.
> 
> Aside, from this recommendation notice that the commands for MLPerf inference benchmark are suggested in the README under Run Local section. I would try them first before experimenting with custom commands.

you are right!
torch.cuda.is_available() I got False
I changed the version of the graphics driver
and it worked!!
Thank you very much

**Comment by mnaumovfb** [comment]
Closing.
