### ISSUE TITLE
arch-embedding-size for criteo database

### ISSUE THREAD

**Issue by DUKaige** [facebookresearch/dlrm#123]
I'm trying to perform an experiment equivalent to DLRM in Alibaba's XDL. Could you provide the numbers available for the arch-embedding-size parameter is for the complete Criteo Terabyte Dataset including all 24 days?

**Comment by mnaumovfb** [comment]
The `--arch-embedding-size` is obtained from the data, although it could be capped at `--max-ind-range` for each embedding. You can find the sizes used for MLPerf benchmark runs [here](https://github.com/mnaumovfb/inference/blob/master/v0.5/recommendation/python/main.py#L189).

**Comment by mnaumovfb** [comment]
Closing.
