### ISSUE TITLE
Preprocessing the Terabyte Dataset

### ISSUE THREAD

**Issue by JulianToya** [facebookresearch/dlrm#125]
Hey there,

I have a system that currently has 375 GB of memory and 2.9 TB of storage at the moment and hope to preprocess the Terabyte Dataset and do a little benchmarking of the training of the model. I have read that the amount of memory I have should be sufficient for my needs but that you want roughly 3-4 times that of the uncompressed unprocessed dataset (1 TB) as storage in order to preprocess it. 

Unfortunately, I found this out after it crashed at the reordering step (assuming not enough space) but after looking at the data_utils.py script, I was wondering if it was safe to delete the uncompressed and compressed (npz) day files and just rerun it or do I just need to bite the bullet and expand my storage. I just wanted to see if this was an option (and not accidentally reset the 5-6 day process by deleting things without regard.

Any and all help is much appreciated!

**Comment by mnaumovfb** [comment]
I would say that your system is on the edge of what would be needed to pre-process the Criteo Terabyte dataset. You have a couple of options for pre-processing
1. the default loader (not feasible with your RAM)
2. the default loader and option that minimizes RAM usage (`--memory-map`)
3. the binary data loader (`--mlperf-logging --mlperf-bin-loader --mlperf-bin-shuffle`)

I would probably try option 2 and consider working with reduced embeddings (`--max-ind-range`) and data (`--data-sub-sample-rate`) as a starting point.

Now back to your question about the restarting the pre-processing. This can be very tricky to do correctly. The pre-processing has essentially three stages, resulting in: (i) day_*.npz, (ii) day_*_processed.npz (iii) day_*_reordered.npz. You can only restart on the boundary of these stages, which means that you likely need to delete any intermediate files up to the beginning of the stage (also, be careful with two small files day_fea_count.npz and day_day_count.npz they are very important).

**Comment by JulianToya** [comment]
Thank you, understood!

Other than the deleting the intermediate files generated in stage _(iii)_ (after crashing), is it safe to delete any file from stages _(i)_ and _(ii)_ when trying to restart from that point? In particular, the compressed _(day\_*.npz)_ and uncompressed _(day\_*)_ files?

**Comment by mnaumovfb** [comment]
You should try to leave the files from previous stages as much as possible. Only delete (or temporarily move to another directory) the files from the stage that crashed.

**Comment by JulianToya** [comment]
Thanks! I restarted it successfully after taking your advice and increasing both the memory and storage on the system.
