### ISSUE TITLE
size mismatch loading pretrained model

### ISSUE THREAD

**Issue by ciaranB3** [facebookresearch/dlrm#126]
When trying to load the model "dlrm_emb64_subsample0.875_maxindrange10M_pretrained.pt" from the README, I get the following error. 

>size mismatch for emb_l.1.weight: copying a param with shape torch.Size([36084, 64]) from checkpoint, the shape in current model is torch.Size([38985, 64]).

The same error occurs with most of the other embedding tables too, with different sizes of course. 

The command I used, based on bench/dlrm_s_criteo_terabyte.sh

`python dlrm_s_pytorch.py --arch-sparse-feature-size=64 --arch-mlp-bot="13-512-256-64" --arch-mlp-top="512-512-256-1" --max-ind-range=10000000 --data-generation=dataset --data-set=terabyte --raw-data-file=./input/day --processed-data-file=./input/terabyte_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=2048 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --test-freq=10240 --memory-map --data-sub-sample-rate=0.875 --load-model="../tb0875_10M.pt" `

**Comment by mnaumovfb** [comment]
A typical cause of such an error is that pre-processing of dataset was done with different flags from the model run. Did you run this command on raw data or did you pre-process data set with another command (perhaps without --memory-map or --data-sub-sample-rate=0.875 flags)?

**Comment by ciaranB3** [comment]
Thanks for the response. The same flags were used but it was possibly an older version of the code, I'll try re-running the preprocessing steps.

**Comment by mnaumovfb** [comment]
Closing.
