### ISSUE TITLE
Mini Batch Size vs Number of Batches

### ISSUE THREAD

**Issue by mahajandivya** [facebookresearch/dlrm#128]
Hi, 

We have been confused about what the difference between mini batch size and number of batches is? 

Furthermore, in the code, does it go through the entire dataset? We gave a large mini batch size and number of batches but it never covered the entire dataset.

**Comment by mnaumovfb** [comment]
The --mini-batch-size always states how many samples should be grouped into a mini-batch.

The --num-batches has different meaning in two distinct scenarios:
1. random/synthetic data
This tells the code how many mini-batches should be generated and therefore conveys the size of the dataset to be generated. This information can also be specified using --data-size, which is counted in number of samples.
2. public data
The size of the dataset is based on the available data. The --num-batches is used to stop the code after processing a fixed number of mini-batches. It is often used for debugging purposes.

**Comment by mahajandivya** [comment]
Thank you for the clarification, just to confirm, if we want to run 1 epoch across 300 K public data, we should set the mini batch size to be of our choice and no number of batches? However, the default of num batches = 1; would that not have an issue?

We want to train dlrm on a dataset and just want to control the epochs we execute for the algorithm.

**Comment by mnaumovfb** [comment]
That is correct. The default value for --num-batches argument is 0, in which case it should be ignored.

**Comment by mnaumovfb** [comment]
I'm assuming this is resolved. Closing.
