### ISSUE TITLE
batch size and mini batch size

### ISSUE THREAD

**Issue by Jazeeeb** [facebookresearch/dlrm#129]
Hi
what's the batch size and mini batch size when you run it using kaggle dataset for training? 
I'm also a bit confused about the definition of iteration in kaggle accuracy during training. is every iteration equivalent to number of batch size multiplies the number of epochs?

and also would you please specify the size of embedding tables using the Kaggle dataset?

**Comment by mnaumovfb** [comment]
The batch and mini-batch size are used interchangeably in the code. They refer to the number of samples aggregated into a mini-batch and can be found by looking at the value of `--mini-batch-size=128` in the running [script](https://github.com/facebookresearch/dlrm/blob/master/bench/dlrm_s_criteo_kaggle.sh). 

The dimension of embedding vectors is set by the value of `--arch-sparse-feature-size=16`, while the number of vectors in the embeddings is found from the data, but can be limited by `--max-ind-range`. You can print `ln_emb` to see it [here](https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L648).

If you are referring to the plots in the README, then you can think of each iteration as being a single mini-batch, although the results are printed at certain `--print-freq`.

**Comment by mnaumovfb** [comment]
I'm assuming this is resolved. Closing.
