### ISSUE TITLE
Run the code with train dataset

### ISSUE THREAD

**Issue by joy80** [facebookresearch/dlrm#13]
Which command is correct
python dlrm_s_pytorch.py --data-generation="dataset" --mini-batch-size=2 --data-size=6 --data-set = "train.txt"
or
python dlrm_s_pytorch.py --data-generation="dataset" --mini-batch-size=2 --data-size=6 --raw-data-file = "train.txt"
or
anything else please suggest

**Comment by dmudiger** [comment]
Hi,

These are the arguments for training with the Kaggle Display Advertising challenge dataset using the raw data file (train.txt) -

python dlrm_s_pytorch.py  --data-generation=dataset --data-set=kaggle --raw-data-file=train.txt --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128

**Comment by joy80** [comment]
Thanks for the help
I'm debugging the code to use it for my own purpose. Any suggestion will be of great help.

**Comment by dmudiger** [comment]
Hi, you can take a look at the  processKaggleCriteoAdData function (https://github.com/facebookresearch/dlrm/blob/master/data_utils.py#L62).
Here the raw data is processed separating out continuous, categorical features as X_int, X_cat and the labels as y and stored. 
"counts" is the number of data-sample for each split.

**Comment by joy80** [comment]
Sir my last query.
After training the model how can I take the output from it or how can I pass input to make prediction for the particular input?

**Comment by dmudiger** [comment]
Hi,

During training, the model can be saved using --save-model=<path/model.pt>
A previously saved model can be loaded using --load-model=<path/model.pt>
Once loaded the model can be evaluated on the test data-set by specifying --inference-only option.

**Comment by joy80** [comment]
First I run this command:
`python3 dlrm_s_pytorch.py --data-generation=dataset --data-set=kaggle --raw-data-file=train_small.txt --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=2 --test-freq=1 --save-model=model.pt`

Then I run this command:
`python3 dlrm_s_pytorch.py --inference-only --load-model="train.pt"`

and getting this error

```
Using CPU...
Loading saved mode train.pt
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 705, in <module>
    dlrm.load_state_dict(ld_model["state_dict"])
  File "/home/miworld/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DLRM_Net:
	Unexpected key(s) in state_dict: "emb_l.3.weight", "emb_l.4.weight", "emb_l.5.weight", "emb_l.6.weight", "emb_l.7.weight", "emb_l.8.weight", "emb_l.9.weight", "emb_l.10.weight", "emb_l.11.weight", "emb_l.12.weight", "emb_l.13.weight", "emb_l.14.weight", "emb_l.15.weight", "emb_l.16.weight", "emb_l.17.weight", "emb_l.18.weight", "emb_l.19.weight", "emb_l.20.weight", "emb_l.21.weight", "emb_l.22.weight", "emb_l.23.weight", "emb_l.24.weight", "emb_l.25.weight". 
	size mismatch for emb_l.0.weight: copying a param with shape torch.Size([17, 2]) from checkpoint, the shape in current model is torch.Size([4, 2]).
	size mismatch for emb_l.1.weight: copying a param with shape torch.Size([49, 2]) from checkpoint, the shape in current model is torch.Size([3, 2]).
	size mismatch for emb_l.2.weight: copying a param with shape torch.Size([83, 2]) from checkpoint, the shape in current model is torch.Size([2, 2]).
	size mismatch for bot_l.0.weight: copying a param with shape torch.Size([3, 13]) from checkpoint, the shape in current model is torch.Size([3, 4]).
	size mismatch for top_l.0.weight: copying a param with shape torch.Size([4, 353]) from checkpoint, the shape in current model is torch.Size([4, 8]).
```
