### ISSUE TITLE
Problem with dynamic_axes names in exported ONNX model

### ISSUE THREAD

**Issue by mneilly-et** [facebookresearch/dlrm#133]
There appears to be a typo in the names used for dynamic axes:

https://github.com/facebookresearch/dlrm/blob/78d70458e71a62a8e0161fc657c7a5e24b4ff24d/dlrm_s_pytorch.py#L1306-L1309

The resulting ONNX file contains the incorrect name 'batch _size' for index and dense_x dim_params while offsets uses 'batch_size':

```
m = onnx.load('dlrm_s_pytorch.onnx')
[(i.name, i.type.tensor_type.shape.dim) for i in m.graph.input]
[('dense_x', [dim_param: "batch _size"
, dim_value: 256
]), ('offsets', [dim_value: 4
, dim_param: "batch_size"
]), ('indices_0', [dim_param: "batch _size"
]), ('indices_1', [dim_param: "batch _size"
]), ('indices_2', [dim_param: "batch _size"
]), ('indices_3', [dim_param: "batch _size"
])]
```

**Comment by mnaumovfb** [comment]
I believe you are right, can you please create PR to fix it?  Thank you.

**Comment by mnaumovfb** [comment]
The fix has been merged. Closing.
