### ISSUE TITLE
External tensors have raw_data

### ISSUE THREAD

**Issue by mneilly-et** [facebookresearch/dlrm#135]
The [ONNX IR document](https://github.com/onnx/onnx/blob/master/docs/IR.md#external-tensor-data)  states:

> The raw data for large constant tensors, such as initializers, MAY be serialised in a separate file. In such a case, the tensor MUST provide the filename relative to the model file and **_MUST NOT use the value fields._** It MAY provide a byte offset and length within that file. It MAY also specify a SHA1 digest of the file. One file MAY contain the data for multiple tensors.

When exporting DLRM to ONNX with the following command:

```
$ python3 ./dlrm_s_pytorch.py --save-onnx --mini-batch-size=3 --num-batches=10 --data-generation=random --arch-mlp-bot=256-128-32 --arch-mlp-top=512-256-1 --arch-sparse-feature-size=32 --arch-embedding-size=100000-100000-100000-100000 --num-indices-per-lookup=5 --num-indices-per-lookup-fixed=True --arch-interaction-op=dot
```

the following error is generated:

> Traceback (most recent call last):
>   File "./dlrm_s_pytorch.py", line 1324, in <module>
>     onnx.checker.check_model(dlrm_pytorch_onnx)
>   File "/home/mneilly/.virtualenvs/machine_learning/lib/python3.7/site-packages/onnx/checker.py", line 93, in check_model
>     C.check_model(model.SerializeToString())
> onnx.onnx_cpp2py_export.checker.ValidationError: Data of TensorProto ( tensor name: bot_l.0.weight) is stored externally and should not have data field.raw_data
> 

because the weights are external tensors AND have raw_data:

```
>>> import onnx
>>> m = onnx.load('dlrm_s_pytorch.onnx')
>>> for i, x in enumerate(m.graph.initializer):
...     print(f"{i:2} {x.name:20} {'EXTERNAL' if x.data_location else 'INTERNAL'} {len(x.raw_data)}")
... 
 0 181                  INTERNAL 1
 1 182                  INTERNAL 1
 2 183                  INTERNAL 1
 3 184                  INTERNAL 1
 4 185                  INTERNAL 8
 5 bot_l.0.bias         INTERNAL 512
 6 bot_l.0.weight       EXTERNAL 131072
 7 bot_l.2.bias         INTERNAL 128
 8 bot_l.2.weight       EXTERNAL 16384
 9 emb_l.0.weight       EXTERNAL 12800000
10 emb_l.1.weight       EXTERNAL 12800000
11 emb_l.2.weight       EXTERNAL 12800000
12 emb_l.3.weight       EXTERNAL 12800000
13 top_l.0.bias         INTERNAL 2048
14 top_l.0.weight       EXTERNAL 86016
15 top_l.2.bias         INTERNAL 1024
16 top_l.2.weight       EXTERNAL 524288
17 top_l.4.bias         INTERNAL 4
18 top_l.4.weight       INTERNAL 1024
>>> >>> print(m.graph.initializer[6])
dims: 128
dims: 256
data_type: 1
name: "bot_l.0.weight"
raw_data: "Q\202<=\325\232\316\274\250.\035>\325t[\276KY\257=\336\227e<\223\353<\275\033\202V=#\227\234=h\010\250\2733\213?\275\326\201\315=\017\030\252\273A-\277\275\\;\317=\227S\316;\212\0323\275\210\244\224\275;Q\217\275\3742\256\274z\272\003:\300Y\002>U\253\t\274\257K%\276N\003\267<\303\251\03
...
\275\364[\252<\205\351\223\274\030\243O\275\363\263\245<\221\370\007\274W\025j=uT\326=\250\360p\275\367\316}\273\037T\032=\206n\034\276$\3218=\300\n.<\334\2104>\274\220\034=\244\020\205\275xi\031\275\357\257\245<\334}\235\274"
external_data {
  key: "location"
  value: "bot_l.0.weight"
}
data_location: EXTERNAL
```

**Comment by mnaumovfb** [comment]
I don't know why the value field is set. I don't recall seeing such an error. It might be a bug in ONNX.

However, I would
1. Ensure that you have the latest nightly version of PyTorch and ONNX installed and then re-try the experiment. Note that this code code has been successfully used with onnxruntime in the context of MLPerf inference, see https://github.com/mlperf/inference/blob/master/recommendation/dlrm/pytorch/python/backend_onnxruntime.py 
2. Also, if your model is less than 2TB in size, you should be able to set the flag use_external_data_format=False

**Comment by mneilly-et** [comment]
It does look like the message went away with this June 12th commit onnx/onnx@09a4e65bb098164491b021ffe563a559fbc1a808 but the raw_data remains for external tensors. I'll take up the issue to the onnx repo.
