### ISSUE TITLE
Exported ONNX model uses wrong size for index tensors

### ISSUE THREAD

**Issue by mneilly-et** [facebookresearch/dlrm#136]
When exporting to ONNX, _dlrm_s_pytorch.py_ passes the dynamic_axes parameter to _torch.onnx.export()_ and sets the size of the index tensors to _batch_size_:

https://github.com/facebookresearch/dlrm/blob/78d70458e71a62a8e0161fc657c7a5e24b4ff24d/dlrm_s_pytorch.py#L1307-L1320

However, the index tensor for each embedding table has a length of _batch_size_ * _num_indices_per_lookup_:

```
$ python3 -m pdb ./dlrm_s_pytorch.py --save-onnx --mini-batch-size=3 --num-batches=10 --data-generation=random --
arch-mlp-bot=256-128-32 --arch-mlp-top=512-256-1 --arch-sparse-feature-size=32 --arch-embedding-size=100000-100000-100000-100000 --num-indices-per-loo
kup=5 --num-indices-per-lookup-fixed=True --arch-interaction-op=dot
(Pdb) b 1318                                                                
Breakpoint 2 at /home/mneilly/Esperanto/dlrm-fork/dlrm_s_pytorch.py:1318
(Pdb) r
...
(Pdb) dynamic_axes
{'dense_x': {0: 'batch_size'}, 'pred': {0: 'batch_size'}, 'offsets': {1: 'batch_size'}, 'indices_0': {0: 'batch_size'}, 'indices_1': {0: 'batch_size'}, 'indices_2': {0: 'batch_size'}, 'indices_3': {0: 'batch_size'}}
(Pdb) [x.shape for x in lS_i_onnx]
[torch.Size([15]), torch.Size([15]), torch.Size([15]), torch.Size([15])]
(Pdb) 
```

**Comment by mnaumovfb** [comment]
Let me consult with a colleague. We will get back to you shortly.

**Comment by mnaumovfb** [comment]
We have used dynamic_axis parameter to allow the ONNX model saved by this code to run with variable batch size during inference. However, we have only tested this code in the context of MLPerf inference [ONNX runtime backend](https://github.com/mlperf/inference/blob/master/recommendation/dlrm/pytorch/python/backend_onnxruntime.py), where one-hot lookups are used and therefore num_indices_per_lookup=1. So, it's possible we have missed something. Is this run crashing?

**Comment by mneilly-et** [comment]
In the provided output, num-indices-per-lookup=5 and mini-batch-size=3 resulting in each tensor in lS_i_onnx having a shape of 15 as shown. When num-indices-per-lookup != 1 use of batch_size for these inputs seems clearly incorrect to me since their shape is mini-batch-size * num-indices-per-lookup, i.e. - not batch_size....

When exporting an ONNX model with:
```
python3 -m pdb ./dlrm_s_pytorch.py --save-onnx --mini-batch-size=3 --num-batches=10 --data-generation=random --arch-mlp-bot=256-128-32 --arch-mlp-top=512-256-1 --arch-sparse-feature-size=32 --arch-embedding-size=100000-100000-100000-100000 --num-indices-per-lookup=5 --num-indices-per-lookup-fixed=True --arch-interaction-op=dot --save-onnx
```

And attempting to load it into onnxruntime, I see the following shape inference error regardless of mini-batch-size=1 or 3:

```
root@b73d7e7986ec:/dlrm# python
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnxruntime as rt
>>> sess = rt.InferenceSession('dlrm_s_pytorch.onnx', rt.SessionOptions())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers or [])
  File "/usr/local/lib/python3.7/dist-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (Concat_114) Op (Concat) [ShapeInferenceError] All inputs to Concat must have same rank
```

This was run with the following Dockerfile using nightly PT and nightly ORT:

```
FROM debian:latest

RUN DEBIAN_FRONTEND=noninteractive apt update && apt install -y python3 python3-pip git cmake protobuf-compiler libprotoc-dev
RUN update-alternatives --install /usr/bin/python python3 /usr/bin/python3 100

RUN pip3 install numpy
RUN pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html

RUN git clone https://github.com/facebookresearch/dlrm.git
RUN cd dlrm && pip3 install -r requirements.txt
RUN pip3 uninstall -y onnx

RUN git clone --recursive https://github.com/onnx/onnx.git \
        && cd onnx \
        && python3 setup.py install

RUN pip3 install ort-nightly
```

**Comment by mnaumovfb** [comment]
If I look at the PyTorch ONNX documentation (search for first and fifth occurrence of "dynamic_axes" in https://pytorch.org/docs/stable/onnx.html#id18), I see that the dictionary specified for dynamic_axes specifies the dimension in which the batch is growing and its name, but it does not necessarily specify the size of the batch.

Let me know if I'm missing something? and where exactly do you think the batch size should be specified?

**Comment by mnaumovfb** [comment]
Looks like this is resolved as much as possible. Closing.
