### ISSUE TITLE
How to use custom dataset based on amazon review dataset

### ISSUE THREAD

**Issue by minhoha** [facebookresearch/dlrm#138]
I made a custom dataset based on Amazon review dataset.

I looks similar to Kaggle dataset like this

<label> <sparse feature #0> <sparse feature #1>

The above dataset is .txt or .csv file.

How can I use this dataset for DLRM??

**Comment by mnaumovfb** [comment]
I similar question has been asked in the following issue https://github.com/facebookresearch/dlrm/issues/101 I would refer you to it.
