### ISSUE TITLE
Is it possible to use user embeddings too? How can we use users in the context of this CTR model with other categorical and numerical features?

### ISSUE THREAD

**Issue by saman-rahbar** [facebookresearch/dlrm#139]

**Comment by mnaumovfb** [comment]
The embeddings can represent arbitrary things. Please read through the discussion in the following issue https://github.com/facebookresearch/dlrm/issues/105 for additional background about it.

**Comment by saman-rahbar** [comment]
> The embeddings can represent arbitrary things. Please read through the discussion in the following issue #105 for additional background about it.

Thank you so much. One more question, I'm trying to make the scheme more personalized by adding users explicit feedbacks for the purpose of e-commence recommendations, is there anything done around that area or anything that can help me go towards that direction with this model? Thanks a lot again.

**Comment by mnaumovfb** [comment]
You will find a lot of scientific literature about this topic in [KDD](https://www.kdd.org/conferences). In particular, you can take a look at our recent [Building Recommender Systems with PyTorch tutorial](https://github.com/pytorch/workshops/tree/master/KDD_2020). That's probably the best place to look for an answer to this type of questions.

**Comment by mnaumovfb** [comment]
It looks like this is resolved. Closing.
