### ISSUE TITLE
Is there any public dataset with multiple indices per lookup?

### ISSUE THREAD

**Issue by huwan** [facebookresearch/dlrm#140]
DLRM accepts multiple indices per lookup, and we can use num_indices_per_lookup option to set it for random dataset.

But for the real-world Kaggle Display Advertising Challenge Dataset, each lookup only has a single index in it, i.e., one-hot lookups are used. (https://github.com/facebookresearch/dlrm/issues/136#issuecomment-719299949, https://github.com/facebookresearch/dlrm/issues/12#issuecomment-508835281)

The embedding table lookup traces from production workloads used in https://arxiv.org/abs/1811.05922, https://arxiv.org/abs/1912.12953 have multiple indices per lookup, but it is not publicly available.

I was wondering if there is any public dataset where each lookup has multiple indices? Thanks.

**Comment by mnaumovfb** [comment]
[Taobao User Behavior Dataset](https://tianchi.aliyun.com/dataset/dataDetail?dataId=649&userId=1) used in [TBSM](https://github.com/facebookresearch/tbsm) should have this property.

**Comment by huwan** [comment]
Got it. Thank you for the prompt reply.

**Comment by m1chaelyeung** [comment]
I was wondering how to use Taobao User Behavior Dataset on DLRM. Specifically, I want to know what would be the input and what would be the output.

**Comment by mnaumovfb** [comment]
The Taobao User Behavior Dataset is not directly connected to DLRM per say, but a related model called TBSM. Please take a look at the section 3.2 in [TBSM paper](https://arxiv.org/abs/2008.11922) listed in the link above for an explanation of it.
