### ISSUE TITLE
more detailed documentation about distributed training 

### ISSUE THREAD

**Issue by initzhang** [facebookresearch/dlrm#147]
there is little content in the README about how to train dlrm distributedly, which seems the highlight of version 1.0

> 5. The code now supports synchronous distributed training, we support gloo/nccl/mpi backend, we provide launching mode for pytorch distributed launcher and Mpirun. For MPI, users need to write their own MPI launching scripts for configuring the running hosts.

For example, is it possible to provide some explanations on how  to train DLRM with 8 GPU on a single machine with NCCL backend?

**Comment by YazhiGao** [comment]
we have updated the documentation and most of the instruction is actually on pytorch launcher manual, plz see the latest trunk for instructions. closing the issue and plz reopen if u have any more concerns.
