### ISSUE TITLE
How to benchmark the pre-trained models with --inference-only?

### ISSUE THREAD

**Issue by suz53** [facebookresearch/dlrm#148]
Hi, I was trying to benchmark the inference performance on the pre-trained models such as tb0875_10M.pt for the Criteo Terabyte Dataset, and tb00_40M.pt for the MLPerf. 

The command line I was using is: `python dlrm_s_pytorch.py --arch-sparse-feature-size=128 --arch-mlp-bot="13-512-256-128" --arch-mlp-top="1024-1024-512-256-1" --max-ind-range=40000000 --loss-function=bce --round-targets=True --learning-rate=1.0 --mini-batch-size=2048 --print-freq=2048 --print-time --test-freq=102400 --test-mini-batch-size=16384 --test-num-workers=16 --inference-only --load-model=tb0875_10M.pt --memory-map --mlperf-auc-threshold=0.8025 --mlperf-bin-loader --mlperf-bin-shuffle 2>&1 | tee run_terabyte_mlperf_pt.log`. 
But errors with *size mismatch*: `size mismatch for emb_l.0.weight: copying a param with shape torch.Size([9980333, 64]) from checkpoint, the shape in current model is torch.Size([4, 128]).`

Could you please provide the commands parameters (with `--inference-only`) for benchmarking the inference performance on these two pre-trained models?

**Comment by mnaumovfb** [comment]
Different loaders will have slightly different way of shuffling the data during pre-processing. This pre-trained models were saved with the default (not mlperf loaders). This is likely the reason why you see a mismatch in embedding size. Please take a look at the following issue https://github.com/facebookresearch/dlrm/issues/141 to see if it helps.

**Comment by suz53** [comment]
Hi, thanks a lot for the reply. I've looked into the previous issue and still cannot run.

I can only access around 55GB storage in a cluster, and that is why I wanted to just perform the inference (`--inference-only`) without training a model by myself. I understand that around 1TB space is required to go through the training and inference. But, could you please let me know is there any possibility of running the inference within the 55GB storage condition? If so, can you please tell me the command line for the `dlrm_emb64_subsample0.875_maxindrange10M_pretrained.pt (12GB)` inference, even with a `random` data generation? I only wanted to know the latency breakdown across stages/layers. Accuracy is not considered now. Thanks again!

**Comment by mnaumovfb** [comment]
I would say that 55GB is a very small amount of memory. Keep in mind that besides the model the code needs to pre-process and load the data as well.

If you run with the flags in issue https://github.com/facebookresearch/dlrm/issues/141, does your run succeed (try to add --inference-only flag to them as well)? If not, what is the exact error log?

**Comment by suz53** [comment]
Hi, thanks for your reply.

I've tried with this command: `python dlrm_s_pytorch.py --arch-sparse-feature-size=64 --arch-mlp-bot="13-512-256-64" --arch-mlp-top="512-512-256-1" --max-ind-range=10000000 --data-generation=random --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=2048 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --inference-only --load-model=tb0875_10M.pt` 

The error log is:

```
Unable to import mlperf_logging,  No module named 'mlperf_logging'
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
world size: 1, current rank: 0, local rank: 0
Using CPU...
Loading saved model tb0875_10M.pt
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 1862, in <module>
    run()
  File "dlrm_s_pytorch.py", line 1377, in run
    dlrm.load_state_dict(ld_model["state_dict"])
  File "/panfs/users/Xzying/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 837, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DLRM_Net:
	Unexpected key(s) in state_dict: "emb_l.3.weight", "emb_l.4.weight", "emb_l.5.weight", "emb_l.6.weight", "emb_l.7.weight", "emb_l.8.weight", "emb_l.9.weight", "emb_l.10.weight", "emb_l.11.weight", "emb_l.12.weight", "emb_l.13.weight", "emb_l.14.weight", "emb_l.15.weight", "emb_l.16.weight", "emb_l.17.weight", "emb_l.18.weight", "emb_l.19.weight", "emb_l.20.weight", "emb_l.21.weight", "emb_l.22.weight", "emb_l.23.weight", "emb_l.24.weight", "emb_l.25.weight". 
	size mismatch for emb_l.0.weight: copying a param with shape torch.Size([9980333, 64]) from checkpoint, the shape in current model is torch.Size([4, 64]).
	size mismatch for emb_l.1.weight: copying a param with shape torch.Size([36084, 64]) from checkpoint, the shape in current model is torch.Size([3, 64]).
	size mismatch for emb_l.2.weight: copying a param with shape torch.Size([17217, 64]) from checkpoint, the shape in current model is torch.Size([2, 64]).
	size mismatch for top_l.0.weight: copying a param with shape torch.Size([512, 415]) from checkpoint, the shape in current model is torch.Size([512, 70]).
```

**Comment by mnaumovfb** [comment]
This is not the command from issue https://github.com/facebookresearch/dlrm/issues/141. For instance, you have missed the options identifying the dataset, i.e.
```
--raw-data-file=./input/day
--processed-data-file=./input/terabyte_processed.npz
```

When the above options are specified the code will create the embedding dimensions based on the data in the dataset. However, when they are not specified the code will take the dimensions from the argument `--arch-embedding-size`, which defaults to `4-3-2`. This is the reason for your latest error: you are loading a model that was trained on the real dataset with corresponding embedding dimensions, but specifying a different model with the command line arguments. 

Please try the command from from issue https://github.com/facebookresearch/dlrm/issues/141 and `--inference-only` flag to it.

**Comment by mnaumovfb** [comment]
It looks like this is resolved. Closing.
