### ISSUE TITLE
How to use the embedding quantization?

### ISSUE THREAD

**Issue by myungkeun-cho** [facebookresearch/dlrm#152]
Hi,
I want to use the embedding quantization.
so I was using "--quantize-emb-with-bit=4" or "--quantize-emb-with-bit=8".
But errors with "args.cluster_flag": "ERROR: 4 and 8-bit quantization with set cluster_flag is not supported".

Here I have two questions.
1. What are "args.cluster_flag" and "args.hype_flags" in "if args.quantize_emb_with_bit in [4, 8]:"?
2. How do I use the "--quantize-emb-with-bit" option?

**Comment by mnaumovfb** [comment]
Please delete the if statements corresponding to cluster_flag (https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L1025) and hype_flag (https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L1037). These are spurious experimental flags.

Then, retry the --quantize-emb-with-bit option and let me know if it works for you.

**Comment by mnaumovfb** [comment]
It looks like it is resolved. Closing.
