### ISSUE TITLE
C++ frontend support

### ISSUE THREAD

**Issue by insoulity** [facebookresearch/dlrm#16]
Hi there,

I wonder if there happens to be a plan to release DLRM written in C++ frontend. In addition, is there any noticeable performance difference between the implementation here and Glow one under the production scale setting?

Thanks,
Yongkee

**Comment by mnaumovfb** [comment]
Hello Yongkee,

We do not have a plan to release a C++ implementation of DLRM at the moment, other than that already implemented with Glow C++ operators https://github.com/pytorch/glow/blob/master/tests/unittests/RecommendationSystemTest.cpp

You can also use Caffe2 C++ operators directly by removing the thin Python layer that wraps them. The Python layer is only present for convenience.

The PyTorch and Caffe2 implementations are very flexible with the dimensions of the architecture defined by command-line arguments. On the other hand, the Glow implementation is a bit more restricted and focused on accelerators. We have not compared them directly.
