### ISSUE TITLE
Loading a saved model result in a key value error

### ISSUE THREAD

**Issue by alshabae** [facebookresearch/dlrm#160]
Thanks for your efforts in making DLRM available to the public. I faced a key value error when loading a pre-trained model. After looking at the code it seems there is a mismatch between keys of the saved model and the loaded one i.e "model_metrics_dict" doesn't have a key-value pair for "total_loss" while  "ld_model" is accessed in the code using "total_loss" key.

**Comment by mnaumovfb** [comment]
What is the exact command and error log?

**Comment by alshabae** [comment]
**This is the command:**

python3 /project/a/b/DLRM/dlrm/dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=/project/a/b/DLRM/Data/train.txt --processed-data-file=/project/a/b/DLRM/Data/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --test-freq=18057 --load-model=/project/a/b/DLRM/Data/model.pt --inference-only --use-gpu

**and this is the error log:**

Unable to import mlperf_logging,  No module named 'mlperf_logging'
Unable to import onnx.  No module named 'onnx'
world size: 1, current rank: 0, local rank: 0
Using 2 GPU(s)...
Reading pre-processed data=/project/a/b/DLRM/Data/kaggleAdDisplayChallenge_processed.npz
Sparse fea = 26, Dense fea = 13
Defined train indices...
Randomized indices across days ...
Split data according to indices...
Reading pre-processed data=/project/a/b/DLRM/Data/kaggleAdDisplayChallenge_processed.npz
Sparse fea = 26, Dense fea = 13
Defined test indices...
Randomized indices across days ...
Split data according to indices...
Loading saved model /project/a/b/DLRM/Data/model.pt
Traceback (most recent call last):
  File "/project/a/b/DLRM/dlrm/dlrm_s_pytorch.py", line 1868, in <module>
    run()
  File "/project/a/b/DLRM/dlrm/dlrm_s_pytorch.py", line 1388, in run
    ld_total_loss = ld_model["total_loss"] 
KeyError: 'total_loss'

**I overcame this error by commenting  all uses of "ld_total_loss" since I only used the pre-trained model for inference**

**Comment by mnaumovfb** [comment]
I guess the next question is how was this model saved? Did you run something like this or something else? 
```
$dlrm_pt_bin --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=/project/a/b/DLRM/Data/train.txt --processed-data-file=/project/a/b/DLRM/Data/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --use-gpu --save-model=/project/a/b/DLRM/Data/model.pt
```

**Comment by myungkeun-cho** [comment]
Hi,
The same problem happens to me.

**This is the command for save the model** :
$dlrm_pt_bin --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./input/train.txt --processed-data-file=./input/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --use-gpu --test-freq=1024 --save-model=./model.pt

**and This is the command for load the model** :
$dlrm_pt_bin --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./input/train.txt --processed-data-file=./input/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --use-gpu --test-freq=1024 --load-model=./model.pt

**This is the error log** :
run pytorch ...
world size: 1, current rank: 0, local rank: 0
Using 1 GPU(s)...
Reading pre-processed data=./input/kaggleAdDisplayChallenge_processed.npz
Sparse fea = 26, Dense fea = 13
Defined train indices...
Randomized indices across days ...
Split data according to indices...
Reading pre-processed data=./input/kaggleAdDisplayChallenge_processed.npz
Sparse fea = 26, Dense fea = 13
Defined test indices...
Randomized indices across days ...
Split data according to indices...
Loading saved model ./model_0226.pt
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 1868, in <module>
    run()
  File "dlrm_s_pytorch.py", line 1388, in run
    ld_total_loss = ld_model["total_loss"]
KeyError: 'total_loss'
done

I just changed the word 'save' to 'load'. The rest of the parameters all used the same thing.

what should I do to solve the problem?

Thank you.

**Comment by mnaumovfb** [comment]
@dkorchevgithub submitted a fix in this commit https://github.com/facebookresearch/dlrm/commit/d25bbc200b58598f359bf3b4bea1654a0deef027

Please re-try and let us know if it works for you.

**Comment by myungkeun-cho** [comment]
Thank you for your quick response.

It works normally after modifying the code as you told me.

Thank you.
