### ISSUE TITLE
unable to download the kaggle dataset

### ISSUE THREAD

**Issue by CRYSTAL3722** [facebookresearch/dlrm#163]
I met with some problems when trying to download the kaggle dataset. The error is shown below. 
<img width="712" alt="微信图片_20210301173657" src="https://user-images.githubusercontent.com/70087469/109479336-3dd57280-7ab5-11eb-9609-537d3ea0783b.png">
I have googled this error, but couldn't find a possible solution in this situation. Is there another way to get the dataset?

**Comment by mnaumovfb** [comment]
Hmmm, not that I know of. I would reach out to the host of the dataset to inquire about it.

**Comment by CRYSTAL3722** [comment]
The above error shows when I come to the downloading page, after clicking on the link given in the readme document. The terabyte dataset is accessible, though.

**Comment by EtoDemerzel0427** [comment]
The dataset can be found here: https://ailab.criteo.com/ressources/.

**Comment by mnaumovfb** [comment]
Thank you for providing an alternative link @EtoDemerzel0427. Please let us know if it works for you @CRYSTAL3722.

**Comment by CRYSTAL3722** [comment]
That works for me! Thanks a lot!
