### ISSUE TITLE
Convert Criteo dataset_binary to another format

### ISSUE THREAD

**Issue by merleyc** [facebookresearch/dlrm#167]
I was wondering if **there is a way some available library/code to convert the Criteo dataset_binary to non-binary format** (example: parquet, libsvm, or csv, etc)?
I have the Criteo preprocessed binary dataset and I was able to load it using [CriteoBinDataset](https://github.com/facebookresearch/dlrm/blob/382d46f353e0f71de43ec3d85caf968bcadc1cb6/data_loader_terabyte.py#L316-L318).

What I understood is that the below code loads the dataset separated by batches. If we take a look into the first set, dataset_binary[0], for example, it has 4 tensor structures. The first one (dataset_binary[0][0]) corresponds to the contiguous features, the last (dataset_binary[0][3]) one to the label, the second and third correspond to the 26 categorical features, both corresponds to original categorical features but preprocessed however I don't understand the **difference between them. Can someone please explain it to me?**
```
dataset_binary = CriteoBinDataset(data_file=binary_data_file,
                                        counts_file=counts_file,
                                        batch_size=2048,)
```

Thank you

**Comment by mnaumovfb** [comment]
I apologize for the late reply, this has somehow slipped through the cracks.

We do not provide such utility. However, you can look at the original dataset text files to understand the feature values/representation in them. Also, the following prior issues https://github.com/facebookresearch/dlrm/issues/22, https://github.com/facebookresearch/dlrm/issues/105 and https://github.com/facebookresearch/dlrm/issues/58 can help.
