### ISSUE TITLE
What does Embedding Vectors mean?

### ISSUE THREAD

**Issue by Jeongmiu** [facebookresearch/dlrm#168]
In #157 , I asked how to access embedding table with indices.
Now I know that.
But, I have new questions about embedding tables.

In #67, **"each unique index maps to a single embedding vector"**
so Embedding table is mapped corresponding to the number of categorical feature values.
for example,
If a categorical feature means **_user's nations_** in any dataset, features may have about 200 country.
Then an embedding table will be consist of about 200 embedding vectors, right?

Question.
If I set the embedding dimension as d = 16, then what does dimensions mean? 
each dimension means meaningful value?
or Are the values ​​of each dimension in the embedding vector composed of 16 random values?

**Comment by mnaumovfb** [comment]
A simple overview of embedding table lookups can be found here. Please take a look at it.
M. Naumov, On the dimensionality of embeddings for sparse features and data, CoRR, 2019 https://arxiv.org/pdf/1901.02103.pdf

**Comment by Jeongmiu** [comment]
Thanks for reply @mnaumovfb 

I want to ask more questions.

From my understanding, The embedding vector maps each categorical value. 
Then, are the vector weights initialized by a **random uniform distribution function**?

The reason I think so is because I saw in the code that the table weights are initialized by the random function.
(dlrm_s_pytorch.py 268 lines)
`W = np.random.uniform(low=-np.sqrt(1/n), high = np.sqrt(1/n), size = (n,m))`


If embedding dimension is **d**,  is the Initial weight of the vector composed of **d-random values**?
and Can I change the embedding table weight range? (Ignore the other influences)

Sorry to continue asking similar questions. 
Thank you in advance.
