### ISSUE TITLE
[Dataset Creation] Python Bug: 'i' format requires -2147483648 <= number <= 2147483647

### ISSUE THREAD

**Issue by mkuchnik** [facebookresearch/dlrm#172]
The multiprocessing code introduced in #117 in susceptible to a multiprocessing bug (of the type in title) that is active in Python3.7 and under. The fix was introduced in https://github.com/python/cpython/pull/10305 ([discussion](https://stackoverflow.com/questions/47776486/python-struct-error-i-format-requires-2147483648-number-2147483647)). Given how long it takes for the dataset conversion to run, it's probably a good idea to document this.

**Comment by amirstar** [comment]
Thank you @mkuchnik! The issue we addressed.
