### ISSUE TITLE
Size and type of embedding vector

### ISSUE THREAD

**Issue by rajesh-iiith** [facebookresearch/dlrm#175]
How do we figure out the size of each entry (vector) in the embedding table and the composition of that embedding vector (data type)?
I saw some embedding bag based implementations which I am not clear about.

**Comment by mnaumovfb** [comment]
The number of vectors in the embedding table is n, and the size of each the vector is m
https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L265
while embedding table weights (values) can be accessed like this
https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L272
