### ISSUE TITLE
The saved model is not created

### ISSUE THREAD

**Issue by hyunsangcho** [facebookresearch/dlrm#176]
Hi. When I run the command with the following options 
![20210423_094022](https://user-images.githubusercontent.com/22744289/115801694-5a888980-a418-11eb-9a95-f102928b157b.png)
(In the above information, I changed it as follows [--nepochs=1 , --save-model=model.pt] and try again. but  result is same)
![20210423_093813](https://user-images.githubusercontent.com/22744289/115801865-ba7f3000-a418-11eb-9245-03562255213c.png)
I couldn't see that the loss was going down. And saved model is not exist. 

But when I try with default option, I was able to confirm thar the model file was saved 
python dlrm_s_pytorch.py
—data-generation=dataset
—data-set=kaggle
—raw-data-file=train.txt
—mini-batch-size=128
—memory-map
—test-mini-batch-size=16384
—test-num-workers=4
—use-gpu
--save-model=model.pt
--test-freq=1024

![1619139050268](https://user-images.githubusercontent.com/22744289/115802199-69237080-a419-11eb-9bc4-d6128041553b.png)

Why is the model not saved in the first attempt I mentioned??

Thanks you

**Comment by Kunkka1988** [comment]
Perhaps the value of is_best from inference() is False.

**Comment by amirstar** [comment]
Saving the model is in this `if` statement https://github.com/facebookresearch/dlrm/blob/2293253241ca067715ae06651a931090b89efc48/dlrm_s_pytorch.py#L1638

 So, the model is saved only when test-freq flag is enabled.
