### ISSUE TITLE
Commit not pushed

### ISSUE THREAD

**Issue by 123nishant** [facebookresearch/dlrm#177]
HI Team, 

I guess this is a bit of a silly question, but I saw 2 formats for apply_emb  : 

1 in master : https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L396
2 in one of the pull requests : https://github.com/facebookresearch/dlrm/blob/52b77f80a24303294a02c86b574529cdc420aac5/dlrm_s_pytorch.py

I want to know if I want to use the version from the pull request , what can be done for that ? 

Also , I saw that it's marked as 'Verified' with multiple changes from various people. 

Isn't it supposed to be merged into the master ? 

I guess it's a basic question , but I couldn't find much in the Git Documentation. 

It would be great if you can help me out here.

**Comment by 123nishant** [comment]
Also in the tutorial of Captum for DLRM [https://github.com/pytorch/captum/blob/master/tutorials/DLRM_Tutorial.ipynb], the apply_emb does not have an argument for ''v_W_l'. 

It mentions that the apply_emb is redefined in https://github.com/facebookresearch/dlrm/blob/52b77f80a24303294a02c86b574529cdc420aac5/dlrm_s_pytorch.py#L276, 
but on following the code in the tutorial , I am not able to use this file. 

I have also edited the file in Colab , yet I wasn't able to proceed as it gave the same error. I have attached a screenshot for the same. 

Can you please help out how I can use the new codes in each instance as mentioned ? 

Thank you.

![image](https://user-images.githubusercontent.com/8594023/116779357-91ebdb80-aa93-11eb-8801-d56b78764ccb.png)

**Comment by mnaumovfb** [comment]
@benghaem and @NarineK could you take a look at this bug?

**Comment by 123nishant** [comment]
HI Team, @benghaem , @NarineK : 

Can you please help with the DLRM tutorial in the Captum Library ??

**Comment by amirstar** [comment]
This is the old version `apply_emb(self, lS_o, lS_i, emb_l)` which is different from the newer one  `apply_emb(self, lS_o, lS_i, emb_l, v_W_l).` The old version was used in the Captum. Could you please apply these two changes and let us know if they work for you: 
1- `def apply_emb(self, lS_o, lS_i, emb_l, v_W_l=None):`  to the line https://github.com/facebookresearch/dlrm/blob/e9b659ecc25952dfbd176e69293ca28954c74c7c/dlrm_s_pytorch.py#L396

2- `if v_W_l and v_W_l[k] is not None:` to the line https://github.com/facebookresearch/dlrm/blob/e9b659ecc25952dfbd176e69293ca28954c74c7c/dlrm_s_pytorch.py#L414

**Comment by 123nishant** [comment]
Thanks @NarineK , 
Looking forward to your comments .

**Comment by mnaumovfb** [comment]
@123nishant did you have a chance to try @amirstar workaround?

**Comment by 123nishant** [comment]
Hi @mnaumovfb , thanks for checking . 
Yes I checked and it worked 
 
Also @NarineK had updated the tutorial , so that worked too 🙂
