### ISSUE TITLE
v_W_l in apply_emb

### ISSUE THREAD

**Issue by 123nishant** [facebookresearch/dlrm#178]
HI Team, 

I searched the web but couldn't find any details regarding this variable  " v_W_l ".

Can you please help out what this means ? 

Also, is there any documentation that I can refer to for the functions in this Repo ?

![image](https://user-images.githubusercontent.com/8594023/117105924-9ddde300-ad9c-11eb-9f13-1603fddc6ef4.png)

**Comment by 123nishant** [comment]
Hi team, can somebody please help me out ?

**Comment by benghaem** [comment]
It holds the the weights for weighted pooling during the lookup stage

Refer "per_sample_weights" in the EmbeddingBag documentation here: 
https://pytorch.org/docs/stable/generated/torch.nn.EmbeddingBag.html#torch.nn.EmbeddingBag

You can enable with the --weighted-pooling flag.

**Comment by 123nishant** [comment]
HI @benghaem , just curious : Do all functions that have been used here, can be traced back to the PyTorch docs ?

**Comment by 123nishant** [comment]
Thanks @benghaem . 
I think this is good enough for me for now.
If required I'll raise another issue for the same.
