### ISSUE TITLE
Weights for categorical multi-hot keys

### ISSUE THREAD

**Issue by mirachakshu** [facebookresearch/dlrm#179]
Hello-- is it possible to model multi-hot categorical inputs along with its weights as inputs? If yes, what would you suggest for its embedding? That is going to be one of the inputs for the recommendation engine.

Thanks,
Mirach

**Comment by mirachakshu** [comment]
Kind of think of it as a dictionary for each item or user.
Word1:weight1
Word2:weight2
...

**Comment by mirachakshu** [comment]
Think of if we had movie genre weights out of 5, instead of just putting genre.

E.g., 
Move : Sixth sense 
-- Genre:
     * horror: 2 out of 5
     * suspense: 4 out of 5
     * Paranormal: 3 out of 5
etc.

**Comment by mirachakshu** [comment]
Hello @mnaumovfb -- sorry about calling you out, but wondering if my question is stupid, or hard, or answered in the past (I went through everything but couldn't find answer, so probably unanswered). Any guidance is appreciated. Thanks.

**Comment by mnaumovfb** [comment]
The [EmbeddingBag](https://pytorch.org/docs/stable/generated/torch.nn.EmbeddingBag.html#torch.nn.EmbeddingBag) operator in PyTorch should allow you to use multi-hot index lookups with weights. Please take a look at `input` and `offsets` and `per_index_weights` inputs as well as `mode` parameter in the documentation.

You will also see these being used here in DLRM code:
https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L265
https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L442

**Comment by mirachakshu** [comment]
Thank you @mnaumovfb - I will review it and try these out. Will reopen if I run into more issues.
