### ISSUE TITLE
Test the model for output

### ISSUE THREAD

**Issue by joy80** [facebookresearch/dlrm#18]
`python dlrm_s_pytorch.py --data-generation=dataset --data-set=kaggle --raw-data-file=train.txt --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --test-freq=10 --save-model=model.pt`

after saving the model by this command how can I get the output from the trained model?
`python dlrm_s_pytorch.py --load-model=model.pt --data-generation=dataset --data-set=kaggle --raw-data-file=test.txt`

is the command is correct for the output purpose?

dlrm_s_pytorch.py line=275
`z = p`
is z is the outputs?
please help !

**Comment by dmudiger** [comment]
Hi, 

For testing on a saved model you should essentially run the same command used for training, with the following additional arguments `--load-model="path to model.pt> --inference-only`
Without the ` --inference-only `argument the save model is treated as an intermediate checkpoint the training resumed from this checkpoint.
For e.g: this is the command that you'd want to use in you case -
`python dlrm_s_pytorch.py --data-generation=dataset --data-set=kaggle --raw-data-file=train.txt --loss-function=bce --round-targets=True --mini-batch-size=128 --load-model=model.pt --inference-only`
This should print out the test loss and accuracy. 

Yes `z` is the output, however it would be best to print it from - https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L746 after the forward pass for each batch.

On a different note, the `--raw-data-file` is needed only for the first time when using the data-set, subsequently you can use the `--processed-data-file `option instead.

Hope this helps!

**Comment by joy80** [comment]
Thanks for your response.
The main thing I want to know that after training the model how to give inputs which are not the part of the test split or the inputs completely are out of the box. How can I pass the inputs with --load-model?

**Comment by joy80** [comment]
One more thing I need to know is how did you define the targets on the kaggle dataset?
In my dataset I'm getting 0 accuracy. I think is it for wrongly defined targets.

**Comment by dmudiger** [comment]
The targets are defined as 1 if clicked and 0 if not.
You can find more details here - https://www.kaggle.com/c/criteo-display-ad-challenge/data
