### ISSUE TITLE
Looking for suggestions to feed multi-dimensional text content LM embedding (like RoBertA embedding) to DLRM

### ISSUE THREAD

**Issue by mirachakshu** [facebookresearch/dlrm#180]
Content part of my recommendation engine depends a lot on text embedding for text for items and users. Is it possible to use Language Model's embedding in there somehow? Would be great if someone has suggestions on how to accomplish that using dense inputs. If I understand correctly, dense inputs are list of single-dimension continuous variable input. But the Language Model embedding would be 64, 128, 256, 512, 1024, etc. dimension embedding. I can potentially use 64 dim embedding, or use T-SNE to map it down to 3-dimensions or so, but if I do that, can I somehow use 3-D vector as the input?

What is your recommendation in that regard that as the input as a single feature, and not 3 different features.

Thanks,

**Comment by mnaumovfb** [comment]
A related question has been asked in https://github.com/facebookresearch/dlrm/issues/101. I would refer you to it.

You can also take a look at [TBSM](https://github.com/facebookresearch/tbsm) for different ways of using DLRM.

**Comment by mirachakshu** [comment]
Thank you @mnaumovfb . Will review and reopen if stuck again.
