### ISSUE TITLE
Preprocess dataset problem

### ISSUE THREAD

**Issue by pmy124** [facebookresearch/dlrm#181]
![image](https://user-images.githubusercontent.com/56997533/118347273-78a75c80-b574-11eb-86a4-32ce4cd7b2c2.png)
I got this error when I try to preprocess the KaggleAdDisplaydataset.
My command is 
python dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=/data/tzachlb/KAGGLE_AD/train.txt --processed-data-file=/model/tzachlb/dlrm/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --use-gpu
And my python version is 3.7
How can I solve this problem?

**Comment by amirstar** [comment]
Hi @pmy124, Thanks for your interest in DLRM. The command runs fine on my side. We have 26 sparse and 13 dense features for Kaggle dataset. Can you please pull the latest code, run the command again and let us know if it works?

**Comment by pmy124** [comment]
Thanks for your generous help! I have tried again in another server, and the problem was solved, so there might be some my own reason.
