### ISSUE TITLE
inference with random dataset

### ISSUE THREAD

**Issue by nzarif** [facebookresearch/dlrm#182]
Hi,

Using the latest version of DLRM I am trying to run inference on random data. The command I am using is like this: 
`python dlrm_s_pytorch.py  --arch-embedding-size=65000-65000-65000-65000-65000-65000-65000-65000 --arch-sparse-feature-size=64 --arch-mlp-bot=1440-720-64 --arch-mlp-top=40-20-10-1 --data-generation=random --mini-batch-size=128 --num-batches=10 --num-indices-per-lookup=32 --num-indices-per-lookup-fixed=True            --inference-only`
This used to work okay with earlier version of DLRM but now I get this error when using `--inference-only`:
`File "dlrm_s_pytorch.py", line 1452, in run
    ), "currently only dataset loader provides testset"
AssertionError: currently only dataset loader provides testset`
Training is totally ok but inference no. Can you please help me to figure out why I am getting this error and how it can be solved?

Thanks

**Comment by amirstar** [comment]
Thanks @nzarif for your interest in DLRM. As it checked here https://github.com/facebookresearch/dlrm/blob/e9b659ecc25952dfbd176e69293ca28954c74c7c/dlrm_s_pytorch.py#L1450 DLRM random option generates a train set but not a test set, while `--inference-only` flag requires us to have a test set. The above combination of options is not supported at the moment.

**Comment by nzarif** [comment]
Hi Amir,

Thanks for your quick response. As far as I know, in previous versions of DLRM, a test set would be generated with the random option too. Are you planning to support that again? Having the random option both for training and inference was enabling system researchers to study DLRM's characteristics from a system point of view which was pretty useful.

**Comment by mnaumovfb** [comment]
I believe I might know the reason for this discrepancy. In the past the inference run would use samples from the training set as inputs, while later we changed it to use samples from the test set. This might have inadvertently changed the behavior of the random data. We can take this as an action item to fix in the future.

**Comment by nzarif** [comment]
Thank you so much! That would be pretty helpful!

**Comment by mnaumovfb** [comment]
@amirstar has made a commit https://github.com/facebookresearch/dlrm/commit/9acb4e1e9bb78995f32a08e76f1299db6a5d6834 that should allow you to run with random data. 

Please give it a try and let us know if it works for you.
