### ISSUE TITLE
why do you use interaction?

### ISSUE THREAD

**Issue by mortezamg63** [facebookresearch/dlrm#183]
Hi
I am wondering why dot product capture interaction. Could you please explain or give me some sources to study and understand what is the intuition of dot product?
How would be the result of classification if we remove the interaction part in the architecture? In fact, It seems to me MLP_TOP captures the interaction among embeddings (features). 

Also, in interaction function, I could not understand why you are using the following lines.
![image](https://user-images.githubusercontent.com/15813546/120899728-04496180-c5e6-11eb-80fa-52b2aea4fe35.png)

I really appreciate help me out to understand your work better.

**Comment by mnaumovfb** [comment]
In my opinion, the best starting point to learn more about recommendation models is the [Matrix Factorization Techniques for Recommender Systems](https://ieeexplore.ieee.org/document/5197422) paper by Y. Koren. The paper touches on multiple topics and discusses dot products as well.

The code snippet you mentioned constructs the indices of elements in the lower triangular part of a matrix that is composed of dot products. Notice that this matrix is symmetric and this avoids picking up duplicates.
