### ISSUE TITLE
why use uniform distribution for emb ?

### ISSUE THREAD

**Issue by Jeongmiu** [facebookresearch/dlrm#185]
`W = np.random.uniform(low = ~ , high = ~ , size = (n,m))`

I saw this code in dlrm(create_emb) code.

Why use the uniform distribution for embedding table weights?

Does it gives better performance by any formula? 

or just use it empirically?

Thanks in advance.

**Comment by mnaumovfb** [comment]
It has been shown empirically to be a reasonable initialization. There is some related theory in the following paper:
X. Glorot and Y. Bengio, "Understanding the difficulty of training deep feedforward neural networks", AISTATS, 2010 http://proceedings.mlr.press/v9/glorot10a/glorot10a.pdf

**Comment by Jeongmiu** [comment]
@mnaumovfb
Thank you, I appreciate it!! :)
