### ISSUE TITLE
Unable to import mlperf_logging

### ISSUE THREAD

**Issue by huwan** [facebookresearch/dlrm#187]
"Unable to import mlperf_logging" occurs due to lack of mlperf_logging.

It would be better to add [mlperf_logging](https://github.com/mlcommons/logging#installation
) to the Requirements section of README.

**Comment by mnaumovfb** [comment]
This package is only required for MLCommons/MLPerf. It's not a general requirement for DLRM and is guarded by [try](https://github.com/facebookresearch/dlrm/blob/2293253241ca067715ae06651a931090b89efc48/mlperf_logger.py#L13) clause.

**Comment by huwan** [comment]
Got it. Closing.
