### ISSUE TITLE
Is there guide to use models for "retrieval stage" (namely candidate generation)

### ISSUE THREAD

**Issue by apdullahyayik** [facebookresearch/dlrm#188]

**Comment by mnaumovfb** [comment]
We don't provide such a  guide for DLRM. The best related resources can probably be found in the KDD conference papers https://kdd.org/conferences

**Comment by apdullahyayik** [comment]
Thank you for your response, as far as I know, there is a candidate
generation mechanism on Instagram app that is based dlrm, however this
Public API is only for re-ranking stage. If you could extend this API to
cover candidates generation, I would appreciate it.

**Comment by mnaumovfb** [comment]
We will take this suggestion as potential future work. Thank you.
