### ISSUE TITLE
there is a bug

### ISSUE THREAD

**Issue by flutgirl** [facebookresearch/dlrm#191]
$ python3 dlrm_s_caffe2.py --mini-batch-size=2 --data-size=6
Traceback (most recent call last):
  File "dlrm_s_caffe2.py", line 1285, in <module>
    offset_to_length_converter=True,
ValueError: too many values to unpack (expected 2)

function make_random_data_and_loader ( in dlrm_data_pytorch.py ) should return 4 values, but  in File "dlrm_s_caffe2.py", line 1284, two are received.
line 1284: train_data, train_ld = dp.make_random_data_and_loader(args, ln_emb, m_den, \

**Comment by amirstar** [comment]
Now Caffe2 version can support random dataset too. Can you please try the latest code and let us know if it works for you?

**Comment by flutgirl** [comment]
OK, it works, thank you!
