### ISSUE TITLE
Update link to Criteo Kaggle Display Advertising Challenge Dataset

### ISSUE THREAD

**Issue by AmandaRP** [facebookresearch/dlrm#193]
The link in the README for the Criteo Kaggle Display Advertising Challenge Dataset no longer provides access to the data.

- Current link: https://labs.criteo.com/2014/02/download-kaggle-display-advertising-challenge-dataset/
- Error when trying to download data: "The specified bucket does not exist"

The data can now be accessed here: http://go.criteo.net/criteo-research-kaggle-display-advertising-challenge-dataset.tar.gz

**Comment by mnaumovfb** [comment]
Thank you for pointing it out. We will update it.

**Comment by mnaumovfb** [comment]
Done
