### ISSUE TITLE
Lifecycle of embedding tables

### ISSUE THREAD

**Issue by rajesh-iiith** [facebookresearch/dlrm#194]
I see that embedding tables are created using the `create_emb` method and are accessed using the `apply_emb` method. However, many things are not clear to me.

1. How/When are embedding tables trained? Is it during the same time MLP layers are trained? Where is the code for embedding table training?
2. How are these final embedding tables stored so that they can be accessed during inference? Are they stored as part of the model? or are they dumped into some file etc? How are they loaded into memory during inference? And where is the corresponding code in the DLRM repo?

**Comment by mnaumovfb** [comment]
1. The MLPs and embeddings tables are trained at the same time. In PyTorch the backward path is implicitly constructed from the forward path and is called here https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L1586
2. The embeddings are stored as a list of PyTorch tensors that are part of the `class DLRM_Net`, either here https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L358 or there https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L1296
