### ISSUE TITLE
How to configure the network to only consume the sparse or continuous features

### ISSUE THREAD

**Issue by rajesh-iiith** [facebookresearch/dlrm#195]
I want to do an experiment, where I want to isolate the effect of sparse and continuous features on the output. Is there an elegant way to turn off the network for sparse (and dense) features without changing the dataset?

**Comment by mnaumovfb** [comment]
We do not have a turn key feature for it, but you can rewrite interactions to only propagate some of the features forward https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L473. You only need to be careful to size the next layer accordingly, see `num_int` in https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L1129
