### ISSUE TITLE
if turn on --enable-profiling, training time slows down

### ISSUE THREAD

**Issue by gnupdev** [facebookresearch/dlrm#197]
Hi!

I got some weird situation.

When i turn on --enable-profiling option, training time is slower than turn off option. 
If we use autograd.profiler, do we get some record overhead?

original training time for 1 itr is 23ms.
turn on --enable-profiling, training time for 1 itr : 43ms

thanks for reading my question.

**Comment by mnaumovfb** [comment]
The profiler overheads are not necessarily related to DLRM. They would probably be better addressed by [PyTorch forums](https://discuss.pytorch.org).
