### ISSUE TITLE
KeyError: 'counts is not a file in the archive'

### ISSUE THREAD

**Issue by AbhimanyuKulkarni** [facebookresearch/dlrm#2]
**Command Running:**
`python3 dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./train.txt --processed-data-file=./kaggle_data/kaggle_day_1.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --print-time --use-gpu | tee run_kaggle_pt.log`

**Full Error Message:**
`Using 1 GPU(s)...TITAN V
Loading kaggle dataset...
Reading from pre-processed data=./kaggle_data/kaggle_day_1.npz
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 491, in <module>
    args.processed_data_file,
  File "/home2/abhiman1/dlrm/dlrm_data_pytorch.py", line 53, in read_dataset
    dataset, num_samples, raw_data, processed_data
  File "/home2/abhiman1/dlrm/data_utils.py", line 417, in loadDataset
    counts = data["counts"]
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 239, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'counts is not a file in the archive'
`

**How did I get here?**
I ran ./bench/dlrm_s_criteo_kaggle.sh (for pytorch) with the same args as above command, except I did not specify the --processed-data-file as I didn't have those. The script pre-processed the data and saved kaggle_day_i.npz (i = 1,2,..,7). After pre-processing, the script failed at line 491 in dlrm_s_pytorch.py in relation to line 98 in data_utils.py:
`with np.load(str(d_path) + "kaggle_day_{0}_processed.npz".format(i)) as data:`

With error:
`./kaggle_data/kaggle_day_1_processed.npz doesn't exist`
(Or something like that, I don't have the exact error message with me).
This might be because the files were stored with a different name (kaggle_day_1.npz).

**What does the kaggle_day_1.npz contain?**
I ran the following script:
```
from numpy import load

data = load('kaggle_day_1.npz')
lst = data.files
for item in lst:
    print(item)
    print(data[item])

```
Output:

```
X_int

[[  1   1   5 ...   2  -1   2]
 [  2   0  44 ...   1  -1   4]
 [  2   0   1 ...   3   3  45]
 ...
 [ -1   4   3 ...   1  -1   3]
 [ -1  -1   0 ...  -1  -1  -1]
 [  0 115   5 ...   2  -1  16]]

X_cat

[['68fd1e64' '80e26c9b' 'fb936136' ... 'c5c50484' 'e8b83407' '9727dd16']
 ['68fd1e64' 'f0cf0024' '6f67f7e5' ... '43f13e8b' 'e8b83407' '731c3655']
 ['287e684f' '0a519c5c' '02cf9876' ... '3b183c5c' '' '']
 ...
 ['05db9164' '8084ee93' '02cf9876' ... '3b183c5c' '' '']
 ['5a9ed9b0' '38a947a1' 'df65428e' ... '4bc4a47f' '' '']
 ['f473b8dc' '09e68b86' '22451e36' ... '3fdb382b' 'e8b83407' '49d68486']]

y

[0 0 0 ... 0 0 0]

```

Clearly, it doesn't contain the field "counts".

**Comment by AbhimanyuKulkarni** [comment]
Sorry about the confusion. It looks like the --processed-data-file should be the file that is created after concatKaggleCriteoAdData is run, which should concatenate the multiple day data into a file and also add the "counts" field.

So I ran the following command:

`python3 dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./train.txt --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --print-time --use-gpu | tee run_kaggle_pt.log`

And got the following error:

```
Using 1 GPU(s)...TITAN V
Loading kaggle dataset...
Saving intermediate data files at ./kaggle_data/
Reading data from path=./train.txt
Total number of datapoints: 45840617
Using exisiting ./kaggle_data/kaggle_day_*.npz files
Using exisiting ./kaggle_data/kaggle_day_*_processed.npz files
Concatinating multiple day kaggle data into ./kaggle_data/kaggleAdDisplayChallenge_processed.npz file
Loaded day: 1 y = 1: 1627580 y = 0: 4921080
Loaded day: 2 y = 1: 3308373 y = 0: 9788947
Loaded day: 3 y = 1: 4978779 y = 0: 14667201
Loaded day: 4 y = 1: 6638644 y = 0: 19555996
Loaded day: 5 y = 1: 8362164 y = 0: 24381136
Loaded day: 6 y = 1: 10044818 y = 0: 29247142
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 491, in <module>
    args.processed_data_file,
  File "/home2/abhiman1/dlrm/dlrm_data_pytorch.py", line 53, in read_dataset
    dataset, num_samples, raw_data, processed_data
  File "/home2/abhiman1/dlrm/data_utils.py", line 396, in loadDataset
    file = getKaggleDisplayAdChallengeDataset(num_samples, df_path, o_filename)
  File "/home2/abhiman1/dlrm/data_utils.py", line 383, in getKaggleDisplayAdChallengeDataset
    o_file = concatKaggleCriteoAdData(split, d_path, o_filename)
  File "/home2/abhiman1/dlrm/data_utils.py", line 113, in concatKaggleCriteoAdData
    with np.load(str(d_path) + "kaggle_counts.npz") as data:
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 372, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './kaggle_data/kaggle_counts.npz'

```

How should I generate the kaggle_counts.npz?

**Comment by mnaumovfb** [comment]
We have fixed this issue in the following commit https://github.com/facebookresearch/dlrm/commit/ff9f9f19831c1aca8dcc9ffb847e29a7716ef4c8

Please try again and let us know if it works.

**Comment by mnaumovfb** [comment]
We will need to add an additional patch for this problem. I will update this thread once it's ready.

**Comment by mnaumovfb** [comment]
We have updated the code with the subsequent commit https://github.com/facebookresearch/dlrm/commit/786fbc9479dc7b2787a5934526024f03f8d15be7

Please try again and let us know if it works.

**Comment by AbhimanyuKulkarni** [comment]
I tried again with the latest commit. It has successfully generated "kaggle_day_i_preprocessed" (i = 1 to 7). However, after that, I get the following error:

```
run pytorch ...
Using 1 GPU(s)...
Loading kaggle dataset...
Saving intermediate data files at ./kaggle_data/
Reading data from path=./train.txt
Total number of datapoints: 45840617
Using existing ./kaggle_data/kaggle_day_*.npz files
Length of convertDicts or counts does not match input shape
Generating convertDicts and counts...
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 489, in <module>
    args.processed_data_file,
  File "/home2/abhiman1/dlrm/dlrm_data_pytorch.py", line 53, in read_dataset
    dataset, num_samples, raw_data, processed_data
  File "/home2/abhiman1/dlrm/data_utils.py", line 429, in loadDataset
    file = getKaggleCriteoAdData(df_path, o_filename)
  File "/home2/abhiman1/dlrm/data_utils.py", line 415, in getKaggleCriteoAdData
    processKaggleCriteoAdData(split, d_path)
  File "/home2/abhiman1/dlrm/data_utils.py", line 88, in processKaggleCriteoAdData
    with np.load(str(d_path) + "kaggle_day_{0}.npz".format(i)) as data:
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 372, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './kaggle_data/kaggle_day_8.npz'

```

I don't get why it is trying to access kaggle_day_8.npz, even though the split = 7.

**Comment by dmudiger** [comment]
Hi, looks like this using previously generated kaggle_day_*.npz files , is this intended ?
Looks like there is mis-match with the previously generated files. 
Can you please try a fresh run with the raw data-file (deleting intermediate files) ? 
or if you already have the concatenated processed files, you could use that with "--processed-data" argument

**Comment by mnaumovfb** [comment]
Also, please make sure you have the latest clean version of the code.

**Comment by AbhimanyuKulkarni** [comment]
It works now. Thanks. I have successfully trained the model to an accuracy of 79.334%. Can I ask you how to now use the trained model for inference? When I run the command:

`python3 dlrm_s_pytorch.py --inference-only --raw-data-file=./test.txt --processed-data-file=./kaggle_data/kaggleAdDisplayChallenge_processed.npz --use-gpu --num-batches=100 --nepochs=1 --data-size=6`

It works, but I get a loss of 0.0000 and accuracy of 0.000%, like so:

`Finished inference it 100/100 of epoch 0, -1.00 ms/it, loss 0.000000, accuracy 0.000 %`

What am I doing wrong?

**Comment by dmudiger** [comment]
Good to know, that it works now.

Currently, we don't yet have support for saving a trained model and using that for inference. 
This feature is work in progress (see: https://github.com/facebookresearch/dlrm/issues/7)
