### ISSUE TITLE
Explanation of parameters

### ISSUE THREAD

**Issue by rajesh-iiith** [facebookresearch/dlrm#201]
Can you please the meaning of these parameters. 
1. **memory-map:** What is the use
2. **data-sub-sample-rate :** How should this value be selected? Does the value of 0.2 mean 20% of the data will be sampled or 80%?
3. How are memory-map and data-sub-sample-rate  related? Should they be used together?
4. **enable-profiling**: What kind of profiling does it do and how is it related to **mlperf-logging**? Can we do mlperf-logging without enable-profiling?

**Comment by mnaumovfb** [comment]
1. `--memory-map` will minimize the RAM required for pre-processing the dataset. It will requires significant discuss space.
2. `--data-sub-sample-rate=0.875` will randomly drop 7/8 = 0.875 of the training samples. 
3. You should be able to combine the two flags.
4. `--enable-profiling` will [profile the runs](https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L1489) and [post-process the results](https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L1766) for you. It is unrelated to the `--mlperf-logging` flag, which creates a log of metrics for MLPerf/MLCommons post-processing scripts.

**Comment by mnaumovfb** [comment]
Closing.

**Comment by tahle** [comment]
> It will require significant discuss space.

What is discuss space?
