### ISSUE TITLE
Missing value imputation

### ISSUE THREAD

**Issue by rajesh-iiith** [facebookresearch/dlrm#202]
Does DLRM data processing infra facilitate missing value imputation?

**Comment by mnaumovfb** [comment]
Can you elaborate on what exactly do you mean? and example would help?

**Comment by rajesh-iiith** [comment]
The data has many missing values. How can we replace the missing values with mean/median/mode etc?

**Comment by mnaumovfb** [comment]
The pre-processing [code](https://github.com/facebookresearch/dlrm/blob/main/data_utils.py#L993) will simply replace the missing values with 0.
