### ISSUE TITLE
flatten tensor takes time on GPU, not CPU

### ISSUE THREAD

**Issue by jdc711** [facebookresearch/dlrm#203]
When measuring the interaction time on CPU vs GPU for inference testing only (running only single GPU), it seems that the interaction time on GPU takes significantly longer than that of the CPU. I found that this single line where Z is flatttened
 :Zflat = Z[:, li, lj] 
takes a significant time on the GPU, but not on the CPU. What could be the cause of this? Thanks

**Comment by mnaumovfb** [comment]
It's possible this operation is not optimized on GPU. Typically interaction would not be the most time consuming part of the computation, so you might want to check how much time does it take relative to other parts of the model, such as MLPs, before spending time optimizing it.

**Comment by mnaumovfb** [comment]
Closing.
