### ISSUE TITLE
Pooling operation in Criteo datasets

### ISSUE THREAD

**Issue by rajesh-iiith** [facebookresearch/dlrm#205]
There is a total of 26 sparse features in the Criteo data sets. Each of these features contains just one value per feature vector resulting in one-hot encoded vectors. Does this mean that for every data point, there will be just one lookup per embedding table and there is no need to do pooling/aggregation? Please clarify if we don't need any aggregation in the case of one-hot encoding.

**Comment by mnaumovfb** [comment]
That is correct, in this particular case there is no pooling.
