### ISSUE TITLE
How to improve training speed?

### ISSUE THREAD

**Issue by rakshithvasudev** [facebookresearch/dlrm#206]
Hello there,

Thanks for open sourcing DLRM. I tried to train from scratch using the `./bench/dlrm_s_criteo_terabyte.sh`. While it was able to train well on all of my GPUs, I wasn't able to use the GPUs fully. I only saw 7-8% utilization on A100-PCIE-40G GPUs. 

Why is the utilization low? Is it because pipeline parallelism needs to be implemented? I think I saw a PR under review for this.

Are there any tips to run this workload faster by utilizing GPUs fully?

**Comment by nikolovn79** [comment]
@rakshithvasudev 

have you run the https://github.com/kamalkraj/dlrm-jax ?

What is the speed per iteration? According to Raj, he gets 7.9 ms/it with GPU ON, and about 10 ms/it without GPU.  My current number is around 5 ms/it.

Finished training it 1024/306969 of epoch 0, **7.90 ms/it**, loss 0.518843
Finished training it 2048/306969 of epoch 0, 7.90 ms/it, loss 0.504157
Finished training it 3072/306969 of epoch 0, 7.87 ms/it, loss 0.498123
Finished training it 4096/306969 of epoch 0, 7.89 ms/it, loss 0.487220
Finished training it 5120/306969 of epoch 0, 7.89 ms/it, loss 0.486305
Finished training it 6144/306969 of epoch 0, 7.92 ms/it, loss 0.481553
Finished training it 7168/306969 of epoch 0, 7.88 ms/it, loss 0.477103
Finished training it 8192/306969 of epoch 0, 7.86 ms/it, loss 0.476559
Finished training it 9216/306969 of epoch 0, 7.86 ms/it, loss 0.474173
Finished training it 10240/306969 of epoch 0, 7.91 ms/it, loss 0.471978

**Comment by mnaumovfb** [comment]
Unfortunately you can not mix `--num-workers` and `--memory-map` flags, see issue https://github.com/facebookresearch/dlrm/issues/159.
