### ISSUE TITLE
How to train with a part of Criteo Kaggle Ad dataset?

### ISSUE THREAD

**Issue by lloydngnn** [facebookresearch/dlrm#208]
This is my log after I run code to train model with Criteo Kaggle Ad dataset:

python dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=/home/loinguyenvan/Projects/Datasets/kaggle-display-advertising-challenge-dataset/train.txt --processed-data-file=./input/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 --test-freq=1024
starship_preexec "$_"
world size: 1, current rank: 0, local rank: 0
Using CPU...
Reading raw data=/home/loinguyenvan/Projects/Datasets/kaggle-display-advertising-challenge-dataset/train.txt
Skipping counts per file (already exist)
Skip existing /home/loinguyenvan/Projects/Datasets/kaggle-display-advertising-challenge-dataset/train_day_0.npz
Skip existing /home/loinguyenvan/Projects/Datasets/kaggle-display-advertising-challenge-dataset/train_day_1.npz
Skip existing /home/loinguyenvan/Projects/Datasets/kaggle-display-advertising-challenge-dataset/train_day_2.npz
Skip existing /home/loinguyenvan/Projects/Datasets/kaggle-display-advertising-challenge-dataset/train_day_3.npz
Skip existing /home/loinguyenvan/Projects/Datasets/kaggle-display-advertising-challenge-dataset/train_day_4.npz
Skip existing /home/loinguyenvan/Projects/Datasets/kaggle-display-advertising-challenge-dataset/train_day_5.npz
Skip existing /home/loinguyenvan/Projects/Datasets/kaggle-display-advertising-challenge-dataset/train_day_6.npz
Total number of samples: 45840617
Divided into days/splits:
 [6548660, 6548660, 6548660, 6548660, 6548659, 6548659, 6548659]
Using existing /home/loinguyenvan/Projects/Datasets/kaggle-display-advertising-challenge-dataset/train_day_0_processed.npz
Using existing /home/loinguyenvan/Projects/Datasets/kaggle-display-advertising-challenge-dataset/train_day_1_processed.npz
Using existing /home/loinguyenvan/Projects/Datasets/kaggle-display-advertising-challenge-dataset/train_day_2_processed.npz
Using existing /home/loinguyenvan/Projects/Datasets/kaggle-display-advertising-challenge-dataset/train_day_3_processed.npz
Using existing /home/loinguyenvan/Projects/Datasets/kaggle-display-advertising-challenge-dataset/train_day_4_processed.npz
Using existing /home/loinguyenvan/Projects/Datasets/kaggle-display-advertising-challenge-dataset/train_day_5_processed.npz
Using existing /home/loinguyenvan/Projects/Datasets/kaggle-display-advertising-challenge-dataset/train_day_6_processed.npz
Concatenating multiple days into /home/loinguyenvan/Projects/Datasets/kaggle-display-advertising-challenge-dataset/kaggleAdDisplayChallenge_processed.npz file
Loaded day: 0 y = 1: 1627580 y = 0: 4921080
Loaded day: 1 y = 1: 3308373 y = 0: 9788947
Loaded day: 2 y = 1: 4978779 y = 0: 14667201
Loaded day: 3 y = 1: 6638644 y = 0: 19555996
Loaded day: 4 y = 1: 8362163 y = 0: 24381136
Loaded day: 5 y = 1: 10044816 y = 0: 29247142
Loaded day: 6 y = 1: 11745438 y = 0: 34095179
Loaded counts!
 Sparse fea = 26, Dense fea = 13
Defined train indices...
Randomized indices across days ...
Killed

![image](https://user-images.githubusercontent.com/84302565/135737820-dd0004b6-f381-4e27-bfe3-1df209d359be.png)
How to change to the code to reduce dataset size, model size to be able to train model with my PC (16gb ram, 8gb vram, 16gb swap mem)

**Comment by mnaumovfb** [comment]
The original Criteo datasets consist of text files with one sample per line. If you want to run on a smaller number of samples you can just remove some of the lines.

Also, DLRM provides an option `--memory-map` that allows you to minimize memory usage at the expense of disk space and `--data-sub-sample-rate` which drops some sample based on given probability.

Please let me know if any of these three options works for you.

**Comment by mnaumovfb** [comment]
I'm assuming this was resolved as we have not heard back in a while. Closing, but please reopen if needed.
