### ISSUE TITLE
How are categorical features encoded from strings to int?

### ISSUE THREAD

**Issue by rajesh-iiith** [facebookresearch/dlrm#210]
I tried to print a sample row before and after preprocessing was done by DLRM.

**Before Preprocessing (reading from the file):**
4       -1      6       1       51      1       4       2       2       1       1     _       1       87552397        b80912da        b9769c83        c874c3e3        25c83c98 fe6b92e5 0adb34fd        51d76abe        a73ee510        fbbf2c95        d83c39bc        f6e5b9ef        9416a599        1adce6ef        387ececc        447c553c        e5ba7672        7119e567  1d04f4a4        a458ea53        20290c31                32c7478e        b3540901        ce62e669        8538ac3f
**After Preprocessing:(reading from X_int and X_cat)**
Dense (Sample Row):  [ 4  0  6  1 51  1  4  2  2  1  1  0  1] Sparse (Sample Row):  [ 14.  63. 351. 301.   0.   1. 387.  14.   0.  42. 353. 341. 322.   0.
 321. 325.   0.  94.  22.   3. 332.   0.   1. 232.  21. 174.]

Count features look fine. But I don't understand the categorical feature encoding from string to int. In my understanding, every unique string token should have a unique integer representation. But in the above example, I am seeing that multiple strings (25c83c98 , a73ee510  and 3 other tokens) are mapped to 0. How is this possible?

**Comment by tim5go** [comment]
To Facebook Research Team, I would also like to know more about how the data pre-processing works.

**Comment by mnaumovfb** [comment]
Your understanding is almost correct, except for a small detail. The unique strings are mapped to unique integer representation _for a particular feature_. So, a string 25c83c98 for the fifth categorical feature will always be mapped to 0 for this feature. This does not prevent a string a73ee510 for the ninth categorical feature to be mapped to 0 for this feature. The uniqueness holds for a feature not across them.
