### ISSUE TITLE
Running DLRM with Terabyte dataset on machine with less than one TB RAM

### ISSUE THREAD

**Issue by rajesh-iiith** [facebookresearch/dlrm#211]
I have checked that the DLRM loads the entire dataset into the memory at once before doing the batch processing. I am wondering how will this setup work while using the Terabyte dataset as machines won't have 1TB RAM. I see that there is an option --memory-map. What does it exactly do? Will the accuracy drop if I use this --memory-map option? 

What is the correct way to run the DLRM with TB dataset on a machine (without subsampling)?

**Comment by mnaumovfb** [comment]
The `--memory-map` flag will split and load data into memory by blocks. It will also perform shuffles in a similar manner. As @tim5go mentioned it will tradeoff RAM for disk space and speed. The statistical performance of the model will not suffer if you choose to use it.

**Comment by rajesh-iiith** [comment]
@mnaumovfb @tim5go If I use --use-gpu flag with --memory-map, should I be bothered about how much memory is available on the GPU? My GPU is running out of memory while I am running DLRM with TB dataset and --memory-map flag.

**Comment by mnaumovfb** [comment]
The use of `--memory-map` flag should not negatively affect the amount of memory you need on GPUs. You'll need 8x32GB GPUs to run the Terabyte dataset.

**Comment by tim5go** [comment]
@mnaumovfb @rajesh-iiith 
I'm not sure the config 8x32GB is exactly right as a minimum requirement, since it still works for me with 1x40GB GPU to run the Terabyte dataset.

**Comment by mnaumovfb** [comment]
I would say my suggestion would be recommended, but perhaps you can push it lower with some settings.
