### ISSUE TITLE
[Question] Purpose and Benefits of Using Bin Data Loader ?

### ISSUE THREAD

**Issue by tim5go** [facebookresearch/dlrm#214]
From previous issues, I know there's an (3rd) option of loading the data in binary format.
https://github.com/facebookresearch/dlrm/issues/125#issuecomment-676574041

> You have a couple of options for pre-processing
> 1. the default loader (not feasible with your RAM)
> 2. the default loader and option that minimizes RAM usage (`--memory-map`)
> 3. the binary data loader (`--mlperf-logging --mlperf-bin-loader --mlperf-bin-shuffle`)
> 
Still, I didn't quite understand the actual benefits it brings by converting the original Criteo Terabyte raw dataset into binary format, which creates an additional step in the data pre-processing process.

I will highly appreciate if someone can explain the thinking behind.

**Comment by mnaumovfb** [comment]
The raw data set is pre-processed by applying [log transformation to the dense inputs](https://github.com/facebookresearch/dlrm/blob/main/data_utils.py#L835), adjusting the [missing indices to be 0](https://github.com/facebookresearch/dlrm/blob/main/data_utils.py#L993) and [associating and index with each hash value](https://github.com/facebookresearch/dlrm/blob/main/data_utils.py#L1144). 

To avoid spending the time on pre-processing each time, the code has an option to save the pre-processed version of the data that can be used for multiple training runs. By using the binary format you can potentially save space and speed up reading of the data.

**Comment by tim5go** [comment]
@mnaumovfb 
Oh.. it makes sense to me now.
Since you have mentioned some data pre-processing techniques used in DLRM, I would like to know if there is a good way to handle missing categorical field in the following scenarios:

1) Data pre-processing (for incomplete data / missing values)
2) Model Inference (for unseen categorical field, says new customer ID, which never appears in the model, i.e. cold start)

**Comment by mnaumovfb** [comment]
1. They are just mapped to zero.
2. This is not something DLRM supports, it assumes all the hash values are part of the training data set.

**Comment by tim5go** [comment]
@mnaumovfb 
Oh... I guess my wordings for point 2 is unclear or misleading.
What I really meant was a **unseen value** in a categorical field.

So, could we can treat an unseen value (e.g. customer ID) as zero or some default dummy value which has already been created and stored in the Field Dictionary during data pre-processing?

**Comment by mnaumovfb** [comment]
This is not something DLRM supports at the moment. You would have to try your own approaches for it. You can look at proceedings of [KDD](https://www.kdd.org) for a scientific literature review on the topic.
