### ISSUE TITLE
Code for Compositional and Mixed Embedding Tricks

### ISSUE THREAD

**Issue by rajesh-iiith** [facebookresearch/dlrm#217]
Does this DLRM repo have the code for the two papers mentioned in the README i.e compositional embeddings and mixed embeddings?

If yes, where is the code, and how to run DLRM with these tricks?

**Comment by mnaumovfb** [comment]
The relevant code is located in https://github.com/facebookresearch/dlrm/tree/main/tricks, while the flags to experiment with these tricks are `--qr-flag`, `--md-flag` and other associated flags [here](https://github.com/facebookresearch/dlrm/blob/main/dlrm_s_pytorch.py#L911).

**Comment by mnaumovfb** [comment]
Closing.
