### ISSUE TITLE
Confusing comment in dlrm_s_pytorch.py

### ISSUE THREAD

**Issue by future-xy** [facebookresearch/dlrm#218]
Hello! I'm a bit confused about one comment in dlrm_s_pytorch.py, while reading the code.
Line 607 warns:
`# of devices must be >= batch size in parallel_forward call`
However, just in line 609, we set
`ndevices = min(self.ndevices, batch_size, len(self.emb_l))`
which means # of devices must be <= batch size and <= # of embedding tables.
So it seems line 607 should replace ">=" with "<=", if I interpret line 609 right.
Thank you for checking this!

**Comment by mnaumovfb** [comment]
For the dense MLPs the batch will be split across devices. This code ensures that each devices has at least one element of the batch on it: 
- suppose that we have a large batch_size (say 1000) and a few devices (say 8), then we will keep the number of devices.
- suppose that we have a small batch_size (say 4) and a a few devices (say 8), then the number of devices will be reset (say to 4).

Similarly for the embedding tables, which are also split across devices. The code ensures that each device has at least one embedding table on it.

Therefore, the comment is indeed incorrect, it should have stated `# of devices must be <= batch size in parallel_forward call`

I'll take this as a typo to fix in the future. Thank you for pointing it out.

**Comment by future-xy** [comment]
Got it, thanks for your quick reply!
