### ISSUE TITLE
What is the structure of data(input and output) 

### ISSUE THREAD

**Issue by dickkky** [facebookresearch/dlrm#22]
What is the structure of data(input and output) ? Could you give me a example?

**Comment by mnaumovfb** [comment]
The output is a single floating point number indicating a probability of a click.

The input consists of dense (continuous) and sparse (categorical) features:
 - A dense feature could simply be a floating point number, with several dense features often aggregated into a vector.
 - A sparse feature could simply be a set of indices (sometimes referred to as IDs). In particular, in Kaggle Display Advertising Challenge Dataset it is a single integer number. Sparse features are often mapped through embeddings.

A simple example is also provided in section 2 of the "Bandana: Using Non-volatile Memory for Storing Deep Learning Models" paper https://arxiv.org/abs/1811.05922, quoting: 
"For example, we can represent users based on the pages they liked. In this case, each page
would correspond to a unique ID, and IDs would be mapped to an element index in a binary vector. For instance, if a user liked pages with the IDs 2 and 4, out of a total number of 5 pages, the user feature vector would be (0,0,1,0,1)."

**Comment by dickkky** [comment]
Thank you so much!
