### ISSUE TITLE
When training all input data(epoch 1), some indices are not accessed.

### ISSUE THREAD

**Issue by gnupdev** [facebookresearch/dlrm#225]
Hi.

i have question about input data.

if i train dataset 1 epoch(total of dataset), do exist indices that do not accessed on embedding table?

Since the size of the embedding table is determined while reading data, I thought that all indices must be accessed at least once.

But when i count all input indices(lS_i), find that some embedding table's indices do not accessed.

do i misunderstand?

**Comment by hrwleo** [comment]
已收到邮件  阿里阿豆故咋一马斯！如未及时回复，请致电15868848097  QQ：812737452
