### ISSUE TITLE
Questions About the Mixed Embedding

### ISSUE THREAD

**Issue by xiaxin1998** [facebookresearch/dlrm#226]
Dear Author,

I read the paper 'Mixed Dimension Embeddings with Application to Memory-Efficient Recommendation Systems'.
It is a good paper and thanks for sharing the codes. But I am confused about the meaning of k in your codes.
In Algorithm 1 in the paper, which is popularity-based dimension sizing, one of the inputs is probability vector.
But I am unclear for how to compute probability vector in Collaborative Filtering case. There are item and user embedding matrices, what dose the probability vector mean?
In your codes,  (k -- (torch.LongTensor) ; Vector of average number of queries per inference).
So that means the number of rows in each block?

Looking forward to your reply.
Thanks!

**Comment by tginart** [comment]
In your data set, you will have an empirical frequency for each item and user. Those are the values you should use for that probability vector. Does that answer your question?
