### ISSUE TITLE
AttributeError: 'CriteoBinDataset' object has no attribute 'num_samples'

### ISSUE THREAD

**Issue by YingHH1** [facebookresearch/dlrm#227]
Hi,

I have encountered the error:

AttributeError: 'CriteoBinDataset' object has no attribute 'num_samples'

The error stems from the below lines of code:

train_data = data_loader_terabyte.CriteoBinDataset(
    data_file=train_file,
    counts_file=counts_file,
    batch_size=args.mini_batch_size,
    max_ind_range=args.max_ind_range
)

mlperf_logger.log_event(key=mlperf_logger.constants.TRAIN_SAMPLES,
                        value=train_data.num_samples)

I was wondering where the attribute 'num_samples' is defined in the code as I could not find it? My guess is from the class torch.utils.data in older PyTorch version? I'm using torch 1.9.0  + cu11.1, and this error occurs when memory_map = True.

Many thanks for the help!

**Comment by hrwleo** [comment]
已收到邮件  阿里阿豆故咋一马斯！如未及时回复，请致电15868848097  QQ：812737452

**Comment by mnaumovfb** [comment]
What is the exact command you are running?

**Comment by huismiling** [comment]
hi, I use num_entries to replace num_samples. It worked.

**Comment by mnaumovfb** [comment]
It seems that a workaround has been found.
