### ISSUE TITLE
Embedding tables smaller than number of unique tokens

### ISSUE THREAD

**Issue by gopikrishnajha** [facebookresearch/dlrm#233]
The number of rows in an embedding table should be same as the number of unique categorical tokens for that specific feature. However, I see that the embedding tables are smaller than the number of tokens.

Here are the number of unique tokens and embedding table sizes per feature (for Kaggle dataset).

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/kumarr3/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/kumarr3/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

  | C1 | C2 | C3 | C4 | C5 | C6 | C7 | C8 | C9 | C10 | C11 | C12 | C13 | C14 | C15 | C16 | C17 | C18 | C19 | C20 | C21 | C22 | C23 | C24 | C25 | C26
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
unique | 1460 | 583 | 10131226 | 2202607 | 305 | 23 | 12517 | 633 | 3 | 93145 | 5683 | 8351592 | 3194 | 27 | 14992 | 5461305 | 10 | 5652 | 2172 | 3 | 7046546 | 17 | 15 | 286180 | 104 | 142571
ln_emb | 1459 | 583 | 6373320 | 1977439 | 305 | 24 | 12513 | 633 | 3 | 92719 | 5681 | 5666264 | 3193 | 27 | 14986 | 4209367 | 10 | 5652 | 2173 | 4 | 5058596 | 18 | 15 | 282062 | 105 | 141594
diff | 1 | 0 | 3757906 | 225168 | 0 | -1 | 4 | 0 | 0 | 426 | 2 | 2685328 | 1 | 0 | 6 | 1251938 | 0 | 0 | -1 | -1 | 1987950 | -1 | 0 | 4118 | -1 | 977

</body>

</html>

As DLRM paper (https://arxiv.org/pdf/1906.00091.pdf) section 5.1 mentions that the model size is 540M parameters, that suggests that values in ln_emb are lesser than expected. 
I am leaving the max-ind-range to it's default value which is -1.
Can you explain how is this possible? I am using the following command line.

```python dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=kaggle/train.txt --processed-data-file=kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=1024 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-freq=10240 --use-gpu --test-num-workers=16 --mlperf-logging --nepochs 4```

**Comment by mnaumovfb** [comment]
How exactly are you counting the unique  indices (categorical tokens)? Is this across training, validation and test sets?

**Comment by gopikrishnajha** [comment]
@mnaumovfb : I counted number of unique tokens by loading the dataset (train.txt: 7 days of data) into a pandas dataframe and counting unique for each column. This is for the entire dataset (All 7 days). These many tokens will indeed lead to 540M (considering embedding vector length: 16) parameters for Kaggle dataset.

I understand that ```ln_emb``` in the DLRM code only reflects the the unique tokens from the train dataset (first 6 days of data). But this leads to only around 380M parameters model. How is DLRM paper saying the Kaggle model has 540M parameters then? Model is built only using train dataset, right?

**Comment by mnaumovfb** [comment]
First, the text file representing the data set has empty spaces/tabs in it for missing features. These features are transformed into token "0". This probably takes care of the "-1" discrepancies in your table.

Second, in our particular case we take the training set and actually use the first 6 days for training, while splitting the last 7th day into validation and test sets. So, it's possible that not all of the tokens you see in the train.txt file might be counted towards the # of embeddings. That's why in some cases #of unique tokens > # of vectors in the embedding table.

**Comment by gopikrishnajha** [comment]
@mnaumovfb In that case, can you recheck the model size for Kaggle dataset reported in the paper. It should not be 540 Millions.
