### ISSUE TITLE
Criteo 1TB Click Logs dataset missing

### ISSUE THREAD

**Issue by SupermicroML** [facebookresearch/dlrm#234]
Hello, the dataset is no longer available from Azure https://ailab.criteo.com/download-criteo-1tb-click-logs-dataset/
Is there a backup somewhere?

**Comment by gopikrishnajha** [comment]
> Hello, the dataset is no longer available from Azure https://ailab.criteo.com/download-criteo-1tb-click-logs-dataset/ Is there a backup somewhere?

I am also facing this issue.

**Comment by yuhaohaoyu** [comment]
Hi DLRMers, I am facing the similar problem. I am looking for a large dataset with large model, or model definitions from rather recent applications. 

Thanks in advance.

**Comment by yuhaohaoyu** [comment]
> Can you try this link? https://labs.criteo.com/2013/12/download-terabyte-click-logs/

Thank you for the pointer. I just tried it. Key contents of that site is 

```
Download:
The dataset is hosted on Azure ML.
Each day can be downloaded at http://azuremlsampleexperiments.blob.core.windows.net/criteo/day_XX.gz, where XX goes from 0 to 23.

The following command downloads all days:
curl -O http://azuremlsampleexperiments.blob.core.windows.net/criteo/day_{`seq -s ‘,’ 0 23`}.gz
```

It ended up that the host is not resolvable (as below). Do I have to download the image in Azure environment (like a VM in azure) ? 

` Could not resolve host: azuremlsampleexperiments.blob.core.windows.net`

**Comment by mnaumovfb** [comment]
I'm not sure, you would need to ask Criteo about it. You can also ask that question on MLPerf/MLCommons forums.

**Comment by yuhaohaoyu** [comment]
> I'm not sure, you would need to ask Criteo about it. You can also ask that question on [MLPerf/MLCommons](https://github.com/mlcommons/inference/tree/master/recommendation/dlrm/pytorch) forums because they use this data set for benchmarking purposes.

Thank you so much @mnaumovfb
