### ISSUE TITLE
How to use dlrm to run pulic datasets?

### ISSUE THREAD

**Issue by m1chaelyeung** [facebookresearch/dlrm#239]
I want to run some other public datasets, such as LastFM, Movielens.  However, i do not know how to preprocess the datasets to get the proper inputs, either the proper output.

**Comment by mnaumovfb** [comment]
I similar question has been asked in the issue https://github.com/facebookresearch/dlrm/issues/101. I would refer you to it.

**Comment by m1chaelyeung** [comment]
Thank you for your reply. I would have a try.
