### ISSUE TITLE
Does `change_lr` really work in torchrec_dlrm?

### ISSUE THREAD

**Issue by zxgx** [facebookresearch/dlrm#250]
I suppose this line would never be reached unless batch size is set to 1, right?

https://github.com/facebookresearch/dlrm/blob/1472d21231305cacdd3cd138025483422b8a9327/torchrec_dlrm/dlrm_main.py#L402

**Comment by narayanan2004** [comment]
@s4ayub is this an issue?

**Comment by s4ayub** [comment]
@zxgx I haven't ran this in a while and the iteration may have been updated but can you explain why batch size would need to be 1 to hit this line?

**Comment by mnaumovfb** [comment]
The last update was more than a month ago. Closing.
