### ISSUE TITLE
Unable to import mlperf_logging,  No module named 'mlperf_logging'

### ISSUE THREAD

**Issue by DuPianggg** [facebookresearch/dlrm#255]
hello
why I still report this error after downloading the mllog package

**Comment by YI-MAX-YAN** [comment]
https://github.com/mlcommons/logging

**Comment by YI-MAX-YAN** [comment]
Installation
Use one of the following ways to install.

For development, you may download the latest version and install from local path:

git clone https://github.com/mlperf/logging.git mlperf-logging
pip install -e mlperf-logging
Install from github at a specific commit (Replace TAG_OR_COMMIT_HASH with actual tag or commit hash):

pip install "git+https://github.com/mlperf/logging.git@TAG_OR_COMMIT_HASH"

**Comment by mnaumovfb** [comment]
Hello @DuPianggg, have you been able to follow the suggestion from @YI-MAX-YAN? did it work for you?

**Comment by mnaumovfb** [comment]
I'm assuming this is resolved. Closing.
