### ISSUE TITLE
File fbgemm_gpu_py.so not found

### ISSUE THREAD

**Issue by davidxiaozhi** [facebookresearch/dlrm#256]
when  I run the next command 
`torchx run -s local_cwd dist.ddp -j 1x2 --script dlrm_main.py `

it failed , i find the log contain the File fbgemm_gpu_py.so not found ,but have install the torchrec
`pip  install  torchrec `

the log messge is :

torchx 2022-07-10 14:45:12 INFO     Log directory not set in scheduler cfg. Creating a temporary log dir that will be deleted on exit. To preserve log directory set the `log_dir` cfg option
torchx 2022-07-10 14:45:12 INFO     Log directory is: /tmp/torchx_2h6ias8i
local_cwd://torchx/dlrm_main-cnww4l13fxwxmc
torchx 2022-07-10 14:45:12 INFO     Waiting for the app to finish...
dlrm_main/0 [0]:File fbgemm_gpu_py.so not found
dlrm_main/0 [1]:File fbgemm_gpu_py.so not found
dlrm_main/0 [0]:/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py:1383: UserWarning: positional arguments and argument "destination" are deprecated. nn.Module.state_dict will not accept them in the future. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
dlrm_main/0 [0]:  warnings.warn(
dlrm_main/0 [0]:
dlrm_main/0 [1]:/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py:1383: UserWarning: positional arguments and argument "destination" are deprecated. nn.Module.state_dict will not accept them in the future. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
dlrm_main/0 [0]:Epoch 0: 0it [00:00, ?it/s]Traceback (most recent call last):
dlrm_main/0 [1]:  warnings.warn(
dlrm_main/0 [0]:  File "dlrm_main.py", line 655, in <module>
dlrm_main/0 [1]:
dlrm_main/0 [0]:    main(sys.argv[1:])
dlrm_main/0 [1]:Epoch 0: 0it [00:00, ?it/s]Traceback (most recent call last):
dlrm_main/0 [0]:  File "dlrm_main.py", line 647, in main
dlrm_main/0 [1]:  File "dlrm_main.py", line 655, in <module>
dlrm_main/0 [0]:    train_val_test(
dlrm_main/0 [1]:    main(sys.argv[1:])
dlrm_main/0 [0]:  File "dlrm_main.py", line 470, in train_val_test
dlrm_main/0 [1]:  File "dlrm_main.py", line 647, in main
dlrm_main/0 [0]:    _train(
dlrm_main/0 [1]:    train_val_test(
dlrm_main/0 [0]:  File "dlrm_main.py", line 403, in _train
dlrm_main/0 [1]:  File "dlrm_main.py", line 470, in train_val_test
dlrm_main/0 [0]:    train_pipeline.progress(combined_iterator)
dlrm_main/0 [0]:  File "/opt/conda/lib/python3.8/site-packages/torchrec/distributed/train_pipeline.py", line 482, in progress
dlrm_main/0 [1]:    _train(
dlrm_main/0 [0]:    self._connect(dataloader_iter)
dlrm_main/0 [1]:  File "dlrm_main.py", line 403, in _train
dlrm_main/0 [0]:  File "/opt/conda/lib/python3.8/site-packages/torchrec/distributed/train_pipeline.py", line 470, in _connect
dlrm_main/0 [1]:    train_pipeline.progress(combined_iterator)
dlrm_main/0 [0]:    _start_data_dist(self._pipelined_modules, batch_i, self._context)
dlrm_main/0 [1]:  File "/opt/conda/lib/python3.8/site-packages/torchrec/distributed/train_pipeline.py", line 482, in progress
dlrm_main/0 [0]:  File "/opt/conda/lib/python3.8/site-packages/torchrec/distributed/train_pipeline.py", line 267, in _start_data_dist
dlrm_main/0 [1]:    self._connect(dataloader_iter)
dlrm_main/0 [0]:    context.input_dist_requests[forward.name] = module.input_dist(
dlrm_main/0 [1]:  File "/opt/conda/lib/python3.8/site-packages/torchrec/distributed/train_pipeline.py", line 470, in _connect
dlrm_main/0 [0]:  File "/opt/conda/lib/python3.8/site-packages/torchrec/distributed/embeddingbag.py", line 312, in input_dist
dlrm_main/0 [1]:    _start_data_dist(self._pipelined_modules, batch_i, self._context)
dlrm_main/0 [0]:    features = features.permute(
dlrm_main/0 [1]:  File "/opt/conda/lib/python3.8/site-packages/torchrec/distributed/train_pipeline.py", line 267, in _start_data_dist
dlrm_main/0 [0]:  File "/opt/conda/lib/python3.8/site-packages/torchrec/sparse/jagged_tensor.py", line 971, in permute
dlrm_main/0 [1]:    context.input_dist_requests[forward.name] = module.input_dist(
dlrm_main/0 [0]:    ) = torch.ops.fbgemm.permute_2D_sparse_data(
dlrm_main/0 [1]:  File "/opt/conda/lib/python3.8/site-packages/torchrec/distributed/embeddingbag.py", line 312, in input_dist
dlrm_main/0 [0]:  File "/opt/conda/lib/python3.8/site-packages/torch/_ops.py", line 191, in __getattr__
dlrm_main/0 [1]:    features = features.permute(
dlrm_main/0 [0]:    op = torch._C._jit_get_operation(qualified_op_name)
dlrm_main/0 [1]:  File "/opt/conda/lib/python3.8/site-packages/torchrec/sparse/jagged_tensor.py", line 971, in permute
dlrm_main/0 [0]:RuntimeError: No such operator fbgemm::permute_2D_sparse_data
dlrm_main/0 [1]:    ) = torch.ops.fbgemm.permute_2D_sparse_data(
dlrm_main/0 [1]:  File "/opt/conda/lib/python3.8/site-packages/torch/_ops.py", line 191, in __getattr__
dlrm_main/0 [1]:    op = torch._C._jit_get_operation(qualified_op_name)
dlrm_main/0 [1]:RuntimeError: No such operator fbgemm::permute_2D_sparse_data
dlrm_main/0 [0]:
dlrm_main/0 [1]:
dlrm_main/0 [0]:Epoch 0: 0it [00:00, ?it/s]
dlrm_main/0 [1]:Epoch 0: 0it [00:00, ?it/s]
dlrm_main/0 ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 6528) of binary: /opt/conda/bin/python
dlrm_main/0 Traceback (most recent call last):
dlrm_main/0   File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
dlrm_main/0     return _run_code(code, main_globals, None,
dlrm_main/0   File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
dlrm_main/0     exec(code, run_globals)
dlrm_main/0   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 765, in <module>
dlrm_main/0     main()
dlrm_main/0   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
dlrm_main/0     return f(*args, **kwargs)
dlrm_main/0   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
dlrm_main/0     run(args)
dlrm_main/0   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
dlrm_main/0     elastic_launch(
dlrm_main/0   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
dlrm_main/0     return launch_agent(self._config, self._entrypoint, list(args))
dlrm_main/0   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
dlrm_main/0     raise ChildFailedError(
dlrm_main/0 torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
dlrm_main/0 ============================================================
dlrm_main/0 dlrm_main.py FAILED
dlrm_main/0 ------------------------------------------------------------
dlrm_main/0 Failures:
dlrm_main/0 [1]:
dlrm_main/0   time      : 2022-07-10_14:45:28
dlrm_main/0   host      : AlgServer.enflame-tech.com
dlrm_main/0   rank      : 1 (local_rank: 1)
dlrm_main/0   exitcode  : 1 (pid: 6531)
dlrm_main/0   error_file: <N/A>
dlrm_main/0   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
dlrm_main/0 ------------------------------------------------------------
dlrm_main/0 Root Cause (first observed failure):
dlrm_main/0 [0]:
dlrm_main/0   time      : 2022-07-10_14:45:28
dlrm_main/0   host      : AlgServer.enflame-tech.com
dlrm_main/0   rank      : 0 (local_rank: 0)
dlrm_main/0   exitcode  : 1 (pid: 6528)
dlrm_main/0   error_file: <N/A>
dlrm_main/0   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
dlrm_main/0 ============================================================
torchx 2022-07-10 14:45:30 INFO     Job finished: FAILED
torchx 2022-07-10 14:45:30 ERROR    AppStatus:
  msg: <NONE>
  num_restarts: 0
  roles: []
  state: FAILED (5)
  structured_error_msg: <NONE>
  ui_url: file:///tmp/torchx_2h6ias8i/torchx/dlrm_main-cnww4l13fxwxmc

**Comment by narayanan2004** [comment]
Has resolving https://github.com/pytorch/torchrec/issues/557 fixed the issue? You need to install pytorch from stable and fbgemm from stable OR pytorch from nightly + fbgemm from nightly.

**Comment by mnaumovfb** [comment]
The last update was more than a month ago. Closing.
