### ISSUE TITLE
Quantized Inference Accuracy

### ISSUE THREAD

**Issue by dreyx2000** [facebookresearch/dlrm#266]
Have the expected 8-bit quantization and 4-bit quantization (quantization on embedding tables with --quantize-emb-with-bit) inference results for DLRM (Criteo Kaggle in particular) been published somewhere so that I can compare with what I am obtaining? (for example the non-quantized inference results have been published as having accuracy around ~79%).  I am obtaining similar numbers for both 4-bit and 8-bit quantization and this seems counterintuitive to me, so I wanted to validate my results.

edit: removed comment regarding implementation of quantizations as it is not relevant to this issue.

**Comment by mnaumovfb** [comment]
You will find related discussion in the following paper: Z. Deng, et al. [Low-Precision Hardware Architectures Meet Recommendation Model Inference at Scale](https://arxiv.org/abs/2105.12676), IEEE Micro, 2021 

Why do you you think that the results you have obtained are counter intuitive?

**Comment by dreyx2000** [comment]
Thank you for your response.  I am aware of Z. Deng et al.’s paper that you mentioned.  The reason for my question and why I think that my results are counterintuitive is precisely because the paper that you mention states that:

 “More aggressive quantization techniques using 4-bit or even lower bitwidths can potentially bring more capacity savings, but renders the resulting models less likely to meet prescribed accuracy requirement…
…An important observation is that 4-bit quantization results in less quantization errors when used on large embedding tables than on small ones.
…Hence we quantize aggressively with 4-bit the top-N largest embedding tables only. In this way, we increase the compression ratio while keeping quantization error small”

This leads me to believe that in practice 4-bit quantization only should not achieve the same accuracy results as the unquantized or the 8-bit quantized run.
Yet, on my runs I have obtained accuracies of 78.799% with --quantize-emb-with-bit=8, and 78.806% with --quantize-emb-with-bit=4 (I assume noise is responsible for q4 minuscule higher value).

Or maybe I am doing it wrong?  The command used is:

python dlrm_s_pytorch.py --inference-only --load-model=[saved trained model] --quantize-emb-with-bit=[4 or 8] --test-freq=1024 --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=[path of Kaggle train.txt] --processed-data-file=[path of npz file] --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --test-num-workers=16 2>&1 | tee output_log.log 

Or could the reason why I do not observe this difference be because Criteo Kaggle is a smaller dataset and I would observe this difference on the Terabyte dataset? (though I would not think so)

Most thankful for your time!

**Comment by mnaumovfb** [comment]
It's difficult for me to say whether you have a bug or not in your code. This something that you would need to investigate by yourself. For example, you might need to print the quantized values to verify that quantization is indeed happening.

Having said that, I did want to mention that both Criteo datasets are relatively simple and it would not be surprising if 4-bit quantization would work for them. The larger Criteo Terabyte dataset is slightly more complex because it has a different ratio of click and non-clicks in it, and more data, but the "type/format" of the input data is the same.

**Comment by dreyx2000** [comment]
Thank you very much for your response.  I was definitely not looking for you to tell me whether I have a bug or not.  I was looking for insights as to what accuracy I should expect using quantized values.  I even got these results with the unmodified DLRM.   I was just wandering if the accuracy numbers for DLRM 8 and 4 bit quantization for Criteo Kaggle are published anywhere so that I can compare and validate my results.  Yes, I am also investigating these with techniques which do include printing the quantized values and embedding vectors and other such things.  

I think what is happening might have to do with what you state on your second paragraph (that these datasets are relatively simple).  I think that answers my question.

Most thankful for your responses!

I have no further questions or comments.
