### ISSUE TITLE
Output of DLRM model

### ISSUE THREAD

**Issue by agunapal** [facebookresearch/dlrm#268]
Looking at the original paper/blog of DLRM, the output of the model is the click probability in the range [0,1].

However, looking at the implementation here https://github.com/pytorch/torchrec/blob/main/torchrec/models/dlrm.py,

the output seems like a logit. (I am noticing negative values in the output depending on inputs) . Was there a change in implementation?  

Could you please give pointers to why this was changed and what's the usecase?

**Comment by narayanan2004** [comment]
https://github.com/pytorch/torchrec/pull/631 fixes the issue.
