### ISSUE TITLE
Latest DLRM model configuration

### ISSUE THREAD

**Issue by rishucoding** [facebookresearch/dlrm#273]
Hello,

In my research, I am working on performance improvements in DLRM and am interested in knowing the latest DLRM model configurations. 

The Table3 in [ISCA 2022 paper](https://dl.acm.org/doi/pdf/10.1145/3470496.3533727) suggests that newer models are having 10s of MLP layers and 100s of tables. This is a improvement over the  [previous work / ISCA2020](https://arxiv.org/pdf/2001.02772.pdf) where Table 1 suggests only couple of layers. Since both these works are coming from Meta, could you point out or suggest sample configuration adopted in the latest models, particularly: the dimensions of each MLP layer in bottom&top FC stage, and dimension of tables in the embedding stage. This should help me in to obtain the execution time for latest models.

Thanks,
Rishabh Jain

**Comment by mnaumovfb** [comment]
The particular model configuration is related and often dependent on the data set used for training. I believe the largest configuration we have shared for a public data set is in the MLPerf [run_and_time.sh](https://github.com/facebookresearch/dlrm/blob/main/bench/run_and_time.sh) script.

**Comment by mnaumovfb** [comment]
The last update was more than three weeks ago. Closing.

**Comment by rishucoding** [comment]
Thanks @mnaumovfb
