### ISSUE TITLE
Criteo Kaggle Display Advertising Challenge Dataset is missing. Data Processing Problem

### ISSUE THREAD

**Issue by allenfengjr** [facebookresearch/dlrm#274]
Hello, I recently run this program using Criteo Kaggle Display Advertising Challenge Dataset, but it crashed. It appears to be an error in data pre-processing. I paste the error log below. I found that this dataset is no longer available for download at the address provided, so I downloaded the data from another site and I'm not sure if the dataset is correct. [my dataset download website](https://figshare.com/articles/dataset/Kaggle_Display_Advertising_Challenge_dataset/5732310). However, the program successfully generated some processed data which confuses me. Could you please provide the latest dataset downloading website?

run pytorch ...
Unable to import mlperf_logging,  No module named 'mlperf_logging'
world size: 1, current rank: 0, local rank: 0
Using 2 GPU(s)...
Reading raw data=/my_raw_data_path/train.txt
Reading data from path=/ocean/projects/asc200010p/haofeng1/dlrm_dataset/criteo_kaggle/train.txt
Skip existing /my_processed_data_path/train_day_0.npz
Skip existing /my_processed_data_path/train_day_1.npz
Skip existing /my_processed_data_path/train_day_2.npz
Skip existing /my_processed_data_path/train_day_3.npz
Skip existing /my_processed_data_path/train_day_4.npz
Skip existing /my_processed_data_path/train_day_5.npz
Load 4992910/4992911  Split: 0  Label True: 0  Stored: 0
Skip existing /my_processed_data_path/train_day_0.npz
Load 4992909/4992910  Split: 1  Label True: 0  Stored: 0
Skip existing /my_processed_data_path/train_day_1.npz
Load 4992909/4992910  Split: 2  Label True: 1  Stored: 1
Skip existing /my_processed_data_path/train_day_2.npz
Load 4992909/4992910  Split: 3  Label True: 1  Stored: 1
Skip existing /my_processed_data_path/train_day_3.npz
Load 4992909/4992910  Split: 4  Label True: 1  Stored: 1
Skip existing /my_processed_data_path/train_day_4.npz
Load 4992909/4992910  Split: 5  Label True: 0  Stored: 0
Skip existing /my_processed_data_path/train_day_5.npz
Traceback (most recent call last):bel True: 0  Stored: 0
  File "../dlrm_s_pytorch.py", line 1896, in <module>
    run()
  File "../dlrm_s_pytorch.py", line 1106, in run
    train_data, train_ld, test_data, test_ld = dp.make_criteo_data_and_loaders(args)
  File "/jet/home/dlrm/dlrm_data_pytorch.py", line 524, in make_criteo_data_and_loaders
    train_data = CriteoDataset(
  File "/jet/home/dlrm/dlrm_data_pytorch.py", line 110, in __init__
    file = data_utils.getCriteoAdData(
  File "/jet/home/dlrm/data_utils.py", line 1123, in getCriteoAdData
    total_per_file[i] = process_one_file(
  File "/jet/home/dlrm/data_utils.py", line 1011, in process_one_file
    X_cat[i] = np.array(
ValueError: could not broadcast input array from shape (25,) into shape (26,)
done

**Comment by mnaumovfb** [comment]
Please try the links in the following issues https://github.com/facebookresearch/dlrm/issues/163 and https://github.com/facebookresearch/dlrm/issues/193

**Comment by allenfengjr** [comment]
Thank you for your help! The problem is caused by using the wrong dataset. Although these two dataset is very similar from size and description, they are two different datasets.
