### ISSUE TITLE
evaluation for co-located models,

### ISSUE THREAD

**Issue by insoulity** [facebookresearch/dlrm#28]
Hi again,

Is there any way in the current implementation to evaluate co-locating models, as discussed in [1]? If I understand correctly, it seems the current implementation supports for only one model at a time (while being configurable).

If I'd like to reproduce the results, for example, as shown in Figure 8 and 9 [1], I think I need to add yet another dimension to data generator and models creator. 

Please correct me if I miss any. Also any advice for me to implement that feature would be appreciated!

Thanks,
Yongkee

[1] The Architectural Implications of Facebook’s DNN-based Personalized Recommendation

**Comment by alugupta** [comment]
Thanks for the question!

The current code supports only a single DLRM model. In order to study the effects of co-location shown in Figure 8 [1], you can run multiple instances of the code (e.g., running multiple Python interpreters with it).  On the other hand, Figure 9 describes behavior on infrastructure which is not open-sourced.

[1] The Architectural Implications of Facebook’s DNN-based Personalized Recommendation

**Comment by insoulity** [comment]
Udit,

Thanks for the response! I am glad to get your attention.

I agree that I could run multiple instances in a script while I am trying to avoid Python interpreters as much as I can in order to get a better understanding on the model itself. Is it how Figure 8 was generated?

Also, speaking of Figure 9, is there any plan to open-source FBLearner/Predictor at some point?

**Comment by alugupta** [comment]
Hi Yongkee,

Yes, Figure 8 was generated using multiple interpreters. 

To the best of our knowledge, there are no current plans to open-source the infrastructure used in Figure 9.

Udit

**Comment by insoulity** [comment]
Thanks again for the confirmation!

**Comment by insoulity** [comment]
A quick clarification, is there any way to bind each interpreter to a specific CPU (affinity setting)?

**Comment by insoulity** [comment]
A quick clarification, is there any way to bind each interpreter to a specific CPU (affinity setting)?

**Comment by insoulity** [comment]
never mind this. I found it in the given batch script.
