### ISSUE TITLE
Incorrect "No Data in Split" for the last split

### ISSUE THREAD

**Issue by huwan** [facebookresearch/dlrm#33]
It seems that "Number Data in Split" for the last split is incorrect when using Kaggle Criteo Ad Data.

https://github.com/facebookresearch/dlrm/blob/a60b5e614b9dcaab343ec9f2382e6dfa45756fbc/data_utils.py#L388-L399

For example, if the total number of datapoints is 100, "No Data in Split" is 15 for the first 6 splits, but for the last split, it should be 10 = 100-15*6, instead of 15.
```
Total number of datapoints: 100
Loading 14/100   Split: 1   No Data in Split: 15  true label: 0  stored label: 0
Saved kaggle_day_1.npz!
Loading 29/100   Split: 2   No Data in Split: 15  true label: 1  stored label: 1
Saved kaggle_day_2.npz!
Loading 44/100   Split: 3   No Data in Split: 15  true label: 0  stored label: 0
Saved kaggle_day_3.npz!
Loading 59/100   Split: 4   No Data in Split: 15  true label: 0  stored label: 0
Saved kaggle_day_4.npz!
Loading 74/100   Split: 5   No Data in Split: 15  true label: 0  stored label: 0
Saved kaggle_day_5.npz!
Loading 89/100   Split: 6   No Data in Split: 15  true label: 0  stored label: 0
Saved kaggle_day_6.npz!
Loading 99/100   Split: 7   No Data in Split: 15  true label: 0  stored label: 0
Saved kaggle_day_7.npz!
```
PS: Would it be better to change "No Data in Split" to "Number Data in Split"?

**Comment by mnaumovfb** [comment]
I will adjust it in the next commit. Please give me a few days.

**Comment by mnaumovfb** [comment]
This should be fixed in the latest commit. Please let me know if it works for you.

**Comment by huwan** [comment]
It works, thanks.
