### ISSUE TITLE
Are there model weights available for DLRM V2

### ISSUE THREAD

**Issue by mailvijayasingh** [facebookresearch/dlrm#334]
I am trying to run inference for DLRMV2 and it would help to have pre-trained model weights for DLRM V2

**Comment by samiwilf** [comment]
We do not host pre-trained model weights for public access at this time. But we will soon add load/save-model-weights functionality which will allow researchers to create pre-trained model weights.

**Comment by mailvijayasingh** [comment]
Thanks for the response. Are there benchmark scripts for DLRMV2 inference?

**Comment by samiwilf** [comment]
The same code used to benchmark training can be used to benchmark inference only. Just disable training / backprop.  If you are referring to an MLperf benchmark, the MLPerf DLRM V2 inference benchmark is in the works, but I don't have an ETA on when it will be available. It will likely be added to https://github.com/mlcommons/inference.

**Comment by mailvijayasingh** [comment]
> We do not host DLRM v2 pre-trained model weights for public access at this time. But we will soon add load/save-model-weights functionality which will allow researchers to create pre-trained model weights.

Any pointers to how loading and saving weights would help. Will it work similar to loading and saving weights for FSDP models?
