### ISSUE TITLE
GPU Configuration Error

### ISSUE THREAD

**Issue by samhsia** [facebookresearch/dlrm#34]
When I run the following command for testing out the GPU configuration:

`python dlrm_s_caffe2.py --inference-only --use-gpu`

I get the following error message: 

```
 File "dlrm_s_caffe2.py", line 831, in <module>
    device_opt = core.DeviceOption(workspace.GpuDeviceType, 0)
AttributeError: 'module' object has no attribute 'GpuDeviceType'
```

**Comment by mnaumovfb** [comment]
Hmmm, I can not reproduce this error. The same command runs fine for me.

Can you please try running the following two commands and let me know if they work: 
> python dlrm_s_caffe2.py

> export CUDA_VISIBLE_DEVICES=0
> python dlrm_s_caffe2.py --use-gpu

**Comment by mnaumovfb** [comment]
Did you have a chance to try the above commands?

**Comment by mnaumovfb** [comment]
Since I have not heard back in a while, I'm assuming this has been resolved. Closing.

Please feel free to reopen if needed.
