### ISSUE TITLE
how  to  use   memory-map  function

### ISSUE THREAD

**Issue by gukejun1** [facebookresearch/dlrm#343]
How is the memory-map function implemented, how to reduce the memory usage principle, and where is it processed in the dlrm code?

**Comment by mnaumovfb** [comment]
The `--memory-map` flag minimizes the usage of RAM, exchanging it for larger usage of disc space, see issue https://github.com/facebookresearch/dlrm/issues/201. 

It relies on Fisher-Yates-Rao (FYR) shuffle [algorithm](https://github.com/facebookresearch/dlrm/blob/59b489403f6a905eae5b4981c77f153a572676a5/data_utils.py#L557). Its application to shuffling large data sets is explained for example [here](https://blog.janestreet.com/how-to-shuffle-a-big-dataset/)
