### ISSUE TITLE
RuntimeError: [enforce fail at embedding_lookup_idx.cc:215] current == index_size. 0 vs -1. Your input seems to be incorrect: the sum of lengths values should be the size of the indices tensor, but it appears not.

### ISSUE THREAD

**Issue by gukejun1** [facebookresearch/dlrm#352]
But I'm running here.::
embeddings = F.embedding_bag(input_hbm, self.cache_weight_mgr.hbm_cached_weight, offsets, self.max_norm,self.norm_type, self.scale_grad_by_freq, self.mode, self.sparse,per_sample_weights, self.include_last_offset, self.padding_idx)
 bug  appear:                                    
line 2392, in embedding_bag
    ret, _, _, _ = torch.embedding_bag(
RuntimeError: [enforce fail at embedding_lookup_idx.cc:215] current == index_size. 0 vs -1. Your input seems to be incorrect: the sum of lengths values should be the size of the indices tensor, but it appears not.

What is the reason and how to solve it?

**Comment by mnaumovfb** [comment]
Your input into embedding bag operator seems to be corrupted. 
(i) What command are you running?
(ii) What is the content of the offsets?
