### ISSUE TITLE
Memory error while pre processing Criteo Terabyte Dataset

### ISSUE THREAD

**Issue by ddkalamk** [facebookresearch/dlrm#38]
What is the memory requirement for pre processing Criteo Terabyte Dataset? I am getting Memory Error even after having more than a terabyte memory installed on the system.

```
Loaded day: 1 y = 1: 12659815 y = 0: 382745703
Loaded day: 2 y = 1: 18909454 y = 0: 573288083
Loaded day: 3 y = 1: 24713866 y = 0: 748598879
Loaded day: 4 y = 1: 29955964 y = 0: 895472591
Loaded day: 5 y = 1: 35796385 y = 0: 1062180677
Loaded day: 6 y = 1: 42279110 y = 0: 1260544797
Loaded day: 7 y = 1: 48934987 y = 0: 1454689923
Loaded day: 8 y = 1: 55323510 y = 0: 1642073892
Loaded day: 9 y = 1: 61896030 y = 0: 1833925744
Loaded day: 10 y = 1: 68022095 y = 0: 2013577734
Loaded day: 11 y = 1: 73425097 y = 0: 2161763432
Loaded day: 12 y = 1: 79235670 y = 0: 2324956223
Loaded day: 13 y = 1: 85501891 y = 0: 2512906522
Loaded day: 14 y = 1: 91803478 y = 0: 2700686214
Loaded day: 15 y = 1: 97911762 y = 0: 2881732526
Loaded day: 16 y = 1: 103881614 y = 0: 3053747608
Loaded day: 17 y = 1: 109329329 y = 0: 3211682495
Traceback (most recent call last):
  File "cython_criteo.py", line 52, in <module>
    args.memory_map
  File "data_utils_cython.pyx", line 1253, in data_utils_cython.loadDataset
    file = getCriteoAdData(
  File "data_utils_cython.pyx", line 1194, in data_utils_cython.getCriteoAdData
    o_file = concatCriteoAdData(
  File "data_utils_cython.pyx", line 758, in data_utils_cython.concatCriteoAdData
    with np.load(filename_i) as data:
  File "data_utils_cython.pyx", line 764, in data_utils_cython.concatCriteoAdData
    X_cat = np.concatenate((X_cat, data["X_cat"]))
MemoryError

```

**Comment by mnaumovfb** [comment]
I believe you would need at least 2TB to run through with default settings. However, a better alternative is to enable memory mapping with new --memory-map command line option. It will perform reordering and pre-processing without loading all data into memory at once.

Also, please keep in mind that we are still working on this interface. So, it is a work in progress.

**Comment by ddkalamk** [comment]
Ok, thanks. Will wait until it gets stable.

**Comment by alon7** [comment]
@mnaumovfb Hi! I actually had the same error. 
Do I need 2TB of RAM? How much do you think I'll need with the new memory map command? 
I'm not using the Terabyte set but the other, smaller one.
Thanks!

**Comment by mnaumovfb** [comment]
I typically run on a machine with 256GB, but you might be able to get away with 128GB or even 64GB RAM, especially for the smaller dataset.

**Comment by mnaumovfb** [comment]
Just FYI, that the code should be more or less stable for Criteo Terabyte dataset now.

We will continue adding optimizations, but functionally the code works. Please feel free to give it a try with --memory-map and --data-sub-sampling-rate=0.875 options. You should be able to reproduce the plots in the readme.

**Comment by mnaumovfb** [comment]
I believe this has been addressed with the --memory-map option. Closing.
