### ISSUE TITLE
where is the dataset? 

### ISSUE THREAD

**Issue by hyybuaa** [facebookresearch/dlrm#44]
where is the dataset?

**Comment by mnaumovfb** [comment]
Please download the dataset following the links in the README file, listed for convenience below
https://labs.criteo.com/2014/02/kaggle-display-advertising-challenge-dataset/
https://labs.criteo.com/2013/12/download-terabyte-click-logs/

**Comment by mnaumovfb** [comment]
I believe this is resolved. Closing.

**Comment by raydazn** [comment]
how to download dataset ....
