### ISSUE TITLE
Cannot save the model

### ISSUE THREAD

**Issue by JShubhM15** [facebookresearch/dlrm#46]
I am able to train the model successfully with and without GPUs. But, when I try to save the model using "--test-freq=1024 --save-model=./input/model.pt" I don't see any output model being generated.

**Comment by JShubhM15** [comment]
I was able to overcome the problem by setting num of workers to 1. If num of workers are set to anything greater than 1 then I am facing Attribute Error issue. Is this something related to pytorch version. I am using 1.3.1

**Comment by mnaumovfb** [comment]
Hmmm, we have recently fixed an issue with --test-num-workers.
https://github.com/facebookresearch/dlrm/issues/47 

Are you referring to --num-workers or --test-num-workers parameter? and what is the exact output of the error message?

**Comment by mnaumovfb** [comment]
I have not seen a follow up here in some time, so I'm assuming this issue is resolved. If this is not the case, please feel free to reopen it.
