### ISSUE TITLE
Can we run this on a distributed architecture( hadoop) ?

### ISSUE THREAD

**Issue by kapilkd13** [facebookresearch/dlrm#48]
Can we run this on a distributed architecture( hadoop). Also is there a cpu vs gpu benchmarking. Our architecture is completely cpu based but if the gains are large we might attach gpu to it.

**Comment by mnaumovfb** [comment]
We do not currently have a distributed Hadoop or Spark implementation. I can take that as a request for the future. I believe the closest thing right now would be the [FlexFlow](https://github.com/flexflow/FlexFlow) framework implementation listed in the README. 

There are some profiling and runtime numbers in the section 5.2 of [DLRM paper](https://arxiv.org/abs/1906.00091). If you are able to fit the model into a single GPU, then you would probably have a significant advantage, but the exact numbers would depend on your CPU/GPU and PyTorch/Caffe2 frameworks being used.
