### ISSUE TITLE
loadDataset function call is not consistent with its api

### ISSUE THREAD

**Issue by berryweinst** [facebookresearch/dlrm#5]
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 490, in <module>
    args.processed_data_file,
  File "/home/bweinstein/software/Algorithms/dlrm-melrose/dlrm_data_pytorch.py", line 53, in read_dataset
    dataset, num_samples, raw_data, processed_data
TypeError: loadDataset() takes 1 positional argument but 4 were given

**Comment by dmudiger** [comment]
This is an issue that was introduced in the recent PR (https://github.com/facebookresearch/dlrm/commit/ff9f9f19831c1aca8dcc9ffb847e29a7716ef4c8), this has been fixed and the patch should be available shortly

**Comment by mnaumovfb** [comment]
We have fixed this issue in subsequent commit https://github.com/facebookresearch/dlrm/commit/786fbc9479dc7b2787a5934526024f03f8d15be7

Please try again and let us know if it works.

**Comment by berryweinst** [comment]
It works. Thanks.
