### ISSUE TITLE
KeyError: -1758995178

### ISSUE THREAD

**Issue by visioner1128** [facebookresearch/dlrm#57]
Hello, 
I am stuck with a key error in executing the kaggle bench mark.

python dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./input/kaggle/train.txt --processed-data-file=./input/kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --print-time --test-mini-batch-size=16384 --enable-profiling --plot-compute-graph --test-num-workers=16 $dlrm_extra_option 2>&1 | tee run_kaggle_pt.log

Using CPU...
Reading raw data=./input/kaggle/train.txt
Skipping counts per file (already exist)
Skip existing ./input/kaggle/train_day_0.npz
Skip existing ./input/kaggle/train_day_1.npz
Skip existing ./input/kaggle/train_day_2.npz
Skip existing ./input/kaggle/train_day_3.npz
Skip existing ./input/kaggle/train_day_4.npz
Skip existing ./input/kaggle/train_day_5.npz
Skip existing ./input/kaggle/train_day_6.npz
Total number of samples: 45840617
Divided into days/splits:
 [6548660, 6548660, 6548660, 6548660, 6548659, 6548659, 6548659]
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 600, in <module>
    dp.make_criteo_data_and_loaders(args)
  File "/home/junki.park/AXDIMM/dlrm-master/dlrm_data_pytorch.py", line 481, in make_criteo_data_and_loaders
    args.memory_map
  File "/home/junki.park/AXDIMM/dlrm-master/dlrm_data_pytorch.py", line 118, in __init__
    memory_map
  File "/home/junki.park/AXDIMM/dlrm-master/data_utils.py", line 1114, in getCriteoAdData
    processCriteoAdData(d_path, d_file, npzfile, days, convertDicts, counts)
  File "/home/junki.park/AXDIMM/dlrm-master/data_utils.py", line 153, in processCriteoAdData
    X_cat_t[j, k] = convertDicts[j][x]
**KeyError: -1758995178**

To check it in detail,

(jk_env3) junki.park@npu134:~/AXDIMM/dlrm-master$ tail run_kaggle_pt.log
X_cat_t[24,6548655]: 4.0, convertDicts[24][2045441]: 4
k: 6548656, x: 0
X_cat_t[24,6548656]: 1.0, convertDicts[24][0]: 1
k: 6548657, x: 0
X_cat_t[24,6548657]: 1.0, convertDicts[24][0]: 1
k: 6548658, x: 0
X_cat_t[24,6548658]: 1.0, convertDicts[24][0]: 1
k: 6548659, x: -390581241
X_cat_t[24,6548659]: 0.0, convertDicts[24][-390581241]: 0
**k: 0, x: -1758995178**

I am suffering too much because of this problem. Help Me..

**Comment by mnaumovfb** [comment]
In the past I have seen similar errors when something went wrong during the pre-processing of the dataset. For instance, if the pre-processing was interrupted and did not restart cleanly.

I would recommend trying the following
1. Update to the latest version of the code and run from scratch (delete any files aside from train.txt).
2. Simplify the command line as much as possible, I would try
> python dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./input/kaggle/train.txt --processed-data-file=./input/kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --print-time

Let me know if it works.

**Comment by visioner1128** [comment]
Wow.. Thank you.. It works now!
