### ISSUE TITLE
Terabyte dataset

### ISSUE THREAD

**Issue by berryweinst** [facebookresearch/dlrm#58]
Hi,

Is there a chance to upload the preprocessed TeraByte dataset?

Thanks.

**Comment by berryweinst** [comment]
The for loop in the data_utils.py file at line 982 runs forever.

**Comment by mnaumovfb** [comment]
Currently we do not host any pre-processed datasets. The DLRM is in process of being adopted  by MLPerf training benchmark and MLPerf community might be able to do so in the future, though.

Just to put things into perspective, it typically takes several days to pre-process the full Terabyte dataset. You can use --max-ind-range and --data-sub-sample-rate parameters to shrink the size of the model and dataset, respectively.

**Comment by berryweinst** [comment]
I'm trying to reduce the time by the suggested sub-sample-rate as described in your README.md.
I was hoping you already have this preprocessed in some stage of your work on this repo and it might save us these waiting days. Anyway, thanks.

**Comment by tayo** [comment]
I noticed some opportunities for improving pre-processing.  Perhaps the easiest is to use multiprocessing.  There are several expensive loops which are embarassingly parallel.  I think the most critical loop is single-threaded, based on CPU usage in top.  A naive multiprocessing wrap might improve speed by several days.

**Comment by tayo** [comment]
The correct loop to parallelize is likely data_utils.py:1052

**Comment by berryweinst** [comment]
Yes. It should be something like this:

```
    import multiprocessing
    manager = multiprocessing.Manager()
    shared_list = manager.list()

    def per_day_proc(i, shared_list):
        datfile_i = npzfile + "_{0}".format(i)  # + ".gz"
        npzfile_i = npzfile + "_{0}.npz".format(i)
        npzfile_p = npzfile + "_{0}_processed.npz".format(i)
        if path.exists(npzfile_i):
            print("Skip existing " + npzfile_i)
        elif path.exists(npzfile_p):
            print("Skip existing " + npzfile_p)
        else:
            recreate_flag = True
            shared_list[i] = process_one_file(
                datfile_i,
                npzfile,
                i,
                shared_list[i],
            )

    processes = []
    for i in range(days):
        processes.append(multiprocessing.Process(
            target=per_day_proc, args=[i, shared_list]))

    for p in processes:
        p.start()
    for p in processes:
        p.join()
```

**Comment by tayo** [comment]
@berryweinst Yes something like this could work.  Would be interesting to see if it improves your processing time!  Personally, I would consider mulitprocessing.Pool instead of using the multiprocessing.Manager().

For recreate_flag, I would modify the function to return True if it calls process_one_file() and false otherwise.  Then at the caller site, recreate_flag would be something like:

output_booleans = pool.map(per_day_proc, range(days)
recreate_flag = any(output_booleans)

**Comment by berryweinst** [comment]
@tayo I used the manager because it provides a shared list resource built in it. I'm now trying to use it but it seems that it keeps on hanging as the GUI or the shell goes black or goes to sleep. Anyway, it would be much appreciated if the authors could add multiprocessing support.

**Comment by mnaumovfb** [comment]
It's interesting to reflect on how the code has changes over time and how this affected parallelization strategies for pre-processing the data.

First, I wanted to make an important point that in general the processing of multiple days is not embarrassingly parallel. We use dictionaries to associate an index with each unique hash value, and we process the hash values in order of appearance over multiple days. Therefore, if the days are processed completely independently the indices might be assigned out of order, but more importantly the same hash value might be assigned a different index on different days.

The use of dictionaries in the code was refactored multiple times to improve modularity and speed. In the current incarnation the dictionaries are built in two stages:
(1) the dictionary keys are created (using hash values) - data_utils.py:1009
(2) the dictionary values (indices corresponding to the keys) are assigned - data_utils.py:1082
The key collisions are resolved in (1), while the key ordering is assigned in (2). 

I'm not familiar enough with python multi-processing environments (either multiprocessing manager or pool), to say whether the collisions on the same keys (hash values across multiple days) will be resolved correctly by the proposed multiprocessing code. Notice that the each process will call into "per_day_proc" -> "process_one_file", with later routine using global dictionaries where the collisions would happen.

@tayo and @berryweinst Any comments?

**Comment by renganxu** [comment]
It seems data_utils.py requires lots of memory. The script concatenate all files in memory. My system has 384GB, but the program gets killed when concatenating day 4 processed file. How large memory is needed? At least 1 TB? Or is there other solution?

**Comment by mnaumovfb** [comment]
I don't think the above question is related to the threading discussion, but I will answer it here.

In general, you should be able to use the --memory-map flag to limit the memory usage. I ran successfully on a system with 256GB with this flag in the past.

**Comment by tayo** [comment]
@mnaumovfb , re: your comment on Feb 24 -- I think I see your point.  Maintaining the order that the samples are listed does impose serialization.  I agree that the coarse structure that I described earlier would not work.

However, I believe that a lot of this work is very parallel, particularly the CSV parsing?  Consider the [process_one_file](https://github.com/facebookresearch/dlrm/blob/7e6dce57c05a29d2bf74b5d64733db55f78f92c8/data_utils.py#L966) function -- Most of the expensive loop is parallel work, except for the convertDicts, which implicitly maintains the order.  Do I read that correctly?  

One idea -- parallelize the parsing of the giant text files and building up X_cat and X_int -- e.g. one thread per day of data.  Consider the problem of constructing convertDicts separately. After constructing X_cat and X_int for each day, then iterate over the days in a separate sequential loop and build up convertDicts.  Thoughts?

**Comment by tayo** [comment]
Another quick question @mnaumovfb . 

> we process the hash values in order of appearance over multiple days.

Where does the cross-day interaction happen?  The code where you assign contiguous integer indices is [here](https://github.com/facebookresearch/dlrm/blob/7e6dce57c05a29d2bf74b5d64733db55f78f92c8/data_utils.py#L1080).  The dictionaries are still considered for each day separately.  What am I missing?

**Comment by mnaumovfb** [comment]
You are correct that the [process_one_file](https://github.com/facebookresearch/dlrm/blob/7e6dce57c05a29d2bf74b5d64733db55f78f92c8/data_utils.py#L966) is parallel, except for convertDicts. However, the latter dictionary setup is the most expensive part.

- I don't think that the processing X_int and X_Cat separately would help. This would require two passes over the data (rather than one single pass), and you would still be bottlenecked by the [creation of the dictionaries](https://github.com/facebookresearch/dlrm/blob/7e6dce57c05a29d2bf74b5d64733db55f78f92c8/data_utils.py#L1009). 
- In principle, you can parallelize [this loop](https://github.com/facebookresearch/dlrm/blob/7e6dce57c05a29d2bf74b5d64733db55f78f92c8/data_utils.py#L1080) which would help, but I believe the main bottleneck will remain the same (i.e. the [creation of the dictionaries](https://github.com/facebookresearch/dlrm/blob/7e6dce57c05a29d2bf74b5d64733db55f78f92c8/data_utils.py#L1009)). 

What could help the parallelization is if the dictionaries could be created in an atomic fashion, in the sense that two insertions with the same value done in parallel would not result in separate entries, or i multiple dictionaries could be quickly merged together (this would not necessarily preserve the order across days, but might be good enough and equivalent to shuffling the samples).

**Comment by nzarif** [comment]
> The use of dictionaries in the code was refactored multiple times to improve modularity and speed. In the current incarnation the dictionaries are built in two stages:
> (1) the dictionary keys are created (using hash values) - data_utils.py:1009
> (2) the dictionary values (indices corresponding to the keys) are assigned - data_utils.py:1082
> The key collisions are resolved in (1), while the key ordering is assigned in (2).
> 
> 
Each dictionary is representing a sparse (categorical) feature? Assuming the categorical feature being represented is e.g. movie names. What would be the keys and the values in this case? 'cause I'm not exactly getting what indices are representing when we are talking about a categorical feature.

**Comment by mnaumovfb** [comment]
You are correct that there is a dictionary associated with each sparse feature. In your example, you can think of a dictionary simply associating an index with each unique movie name. So, that
(1) the dictionary keys are created (using movie names)
(2) the dictionary values (indices corresponding to keys) are assigned
Ultimately an index will be used to lookup a vector in the embedding table, which will represent a particular movie.

**Comment by nzarif** [comment]
> Ultimately an index will be used to lookup a vector in the embedding table, which will represent a particular movie.
This will give us all the occurrences of that movie in the dataset? If yes, in the same example what is each embedding table storing? e.g. each embedding bag can be storing the data samples from a specific genre of movies?

**Comment by mnaumovfb** [comment]
I'm not sure I understand your question. An embedding table is a two dimensional matrix, say n x d where n is the number of items and d is the dimensions of each vector representing an item. Initially the values of these vectors are random, but as we train the model they are modified through backward propagation to match the data.

**Comment by EtoDemerzel0427** [comment]
@mnaumovfb I assume that in the SLS operation, we have a few (> 1) indices to lookup in each embedding table, as indicated in the DLRM model; however, in the Criteo datasets, the categorical features are encoded to hashed values, after we mapped them to embedding indices, does that mean we will only have a single lookup in each table? If so, will this reflect the production-level situation?

**Comment by mnaumovfb** [comment]
The number of indices in the embedding lookup (SLS) depends on the data. In the Criteo datasets it is indeed 1 but it in general it could be more. If needed you can use random data generation option in DLRM to generate lookups with multiple indices. You can also choose to connect the model to different datasets with many indices per lookup (e.g. https://github.com/facebookresearch/tbsm).

**Comment by mnaumovfb** [comment]
I think the discussion here has been finished. Closing.
