### ISSUE TITLE
RuntimeError: [enforce fail at init.cc:88] success. Failed to run some init functions for caffe2

### ISSUE THREAD

**Issue by visioner1128** [facebookresearch/dlrm#61]
Hello.
I succeeded to profile in the python version code.
However, I tried to profile in the same caffe2 code but got the following error. ()

python dlrm_s_caffe2.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./input/kaggle_caffe2/train.txt --processed-data-file=./input/kaggle_caffe2/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --num-batches=10000 --mini-batch-size=128 --print-freq=100 --print-time **--enable-profiling** --plot-compute-graph --inference-only 

My test environment  is like below.
caffe_master_cudnn_v7.4_cuda10.0 
cudnn_v7.4_cuda10.0 
nccl_2.3.7 
openMPI_v2.1.2 
magma_2.5.0 
python-3.6.6

**Error Log.**

Traceback (most recent call last):
  File "dlrm_s_caffe2.py", line 1056, in <module>
    enable_prof=args.enable_profiling,
  File "dlrm_s_caffe2.py", line 496, in __init__
    workspace.GlobalInit(global_init_opt)
**RuntimeError: [enforce fail at init.cc:88] success. Failed to run some init functions for caffe2.**
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x2b94d3161021 in /home/sr2/junki.park/jk_env/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x49 (0x2b94d3160dc9 in /home/sr2/junki.park/jk_env/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #2: caffe2::GlobalInit(int*, char***) + 0x29c (0x2b949a80689c in /home/sr2/junki.park/jk_env/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #3: <unknown function> + 0x506d7 (0x2b9498dc16d7 in /home/sr2/junki.park/jk_env/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x8c45e (0x2b9498dfd45e in /home/sr2/junki.park/jk_env/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #26: __libc_start_main + 0xf5 (0x2b9477efec05 in /lib64/libc.so.6)
frame #27: python() [0x400bda]

There seems to be an error in the next section of code.
            if enable_prof:
                global_init_opt += [
                    "--logtostderr=0",
                    "--log_dir=./",
                    "--caffe2_logging_print_net_summary=1",
                ]

Do you have anyone to help me?
Thank you.

**Comment by mnaumovfb** [comment]
I don't seem to be able to reproduce this bug on my machine.

Can you try removing the profiling strings that are being added to global_init_opt one-by-one to see which of them causes the error? Also, try running with as few parameters as possible.

**Comment by blairhan** [comment]
I can reproduce the error when I setup the environment as in https://github.com/facebookresearch/dlrm/blob/master/Dockerfile. It seems "log_dir" and "caffe2_logging_print_net_summary" flags don't exist because without them everything works fine.
@mnaumovfb  could you describe your environment, especially pytorch version?

**Comment by mnaumovfb** [comment]
I agree with you, these profiling flags are no longer available. I was able to repro the problem with OSS version of the Caffe2 framework.

I can only suggest to post a question on Caffe2 forums on what is currently the recommended way to profile Caffe2 operators. You can reference this post in it.

**Comment by blairhan** [comment]
@mnaumovfb thanks!
