### ISSUE TITLE
how to get exact Probability

### ISSUE THREAD

**Issue by hoangtubatu123** [facebookresearch/dlrm#62]
I want to train with custom data and get the probability of result. How can???
Thanks

**Comment by mnaumovfb** [comment]
I'm note sure I fully understand the question, but in general this model outputs a single scalar number in the interval [0,1], which can be interpreted as a probability of a click.

**Comment by batrlatom** [comment]
So If I want to use this in recommender system, is the process to predict click for all products in the given context? Or is there any better way like get embeddings for the input and search for closest products via faiss or other similarity search algo?

**Comment by mnaumovfb** [comment]
It all depends on your application. This particular model just predicts a click from a context.

**Comment by batrlatom** [comment]
@mnaumovfb  the application would be recommender for ecommerce website. Maybe I could just get rid of the last layer after the training and get full embeddings as it is done with visual search

**Comment by mnaumovfb** [comment]
You will find a lot of scientific literature about this topic in [KDD](https://www.kdd.org/conferences). Feel free to give it a try.
