### ISSUE TITLE
Adagrad doesn't learn, gradients quickly reaches to zero

### ISSUE THREAD

**Issue by kapilkd13** [facebookresearch/dlrm#64]
Hi, I tried Adagrad as paper mention it to be better performer. But in my case, adagrad is not learning and gradient update quickly reaches to zero. My dataset is balanced, randomized, batch size is good enough(256) and I have tried a range of learning rate. But nothing seems to work. 
What can be the issue and did you guys also faced such issue?
I have around 3k dense features and 50 sparse features. What would you suggest?

Also can we use a combination of Adam and SparseAdam?

**Comment by mnaumovfb** [comment]
I do not recall any major issues using the Adagrad optimizer, other than the fact that at the time it did not have full support for [sparse gradient updates to the embedding tables](https://github.com/facebookresearch/dlrm/issues/15) and therefore was relatively slow.

**Comment by mnaumovfb** [comment]
Closing. Please reopen if needed.
