### ISSUE TITLE
Transforming Kaggle sparse features to multi-hot vectors instead of one-hot vectors

### ISSUE THREAD

**Issue by Otodea** [facebookresearch/dlrm#68]
Hi, 

By default, the sparse features of the Kaggle data become equivalent to one-hot vectors in the DLRM code. Is there any way to instead translate sparse features of Kaggle into multi-hot vectors?

Thank you for your help

**Comment by mnaumovfb** [comment]
I'm not aware of a mapping that does so exactly. However, several techniques for embedding compression, including the [compositional embeddings](https://arxiv.org/abs/1909.02107) break the index range into composite parts that are used to reconstruct the original embeddings approximately.

**Comment by mnaumovfb** [comment]
Closing. Please reopen if needed.
