### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by berryweinst** [facebookresearch/dlrm#7]
Can you please add a pytorch checkpoint save (best validation score) besides onnx?

**Comment by mnaumovfb** [comment]
Sure, no problem. Give us a few days for it.

**Comment by dmudiger** [comment]
model saving, loading and checkpointing support added with https://github.com/facebookresearch/dlrm/pull/8 
Tested for basic functionality, more extensive tests underway - will merge shortly

**Comment by dmudiger** [comment]
PR:https://github.com/facebookresearch/dlrm/pull/8 merged

**Comment by mnaumovfb** [comment]
Please let us know if it works for you. The instructions on how to use it have been added to the readme.

**Comment by berryweinst** [comment]
Works now, thanks.

**Comment by dmudiger** [comment]
Thanks, will go ahead and close this issue.
