### ISSUE TITLE
Caffe2 using 8 GPUs

### ISSUE THREAD

**Issue by berryweinst** [facebookresearch/dlrm#70]
Hi, 
When using 8 GPUs with dlrm_s_caffe2.py it crashes with the following error. When using 4 GPUs out of the 8 it works fine. It seems to be connected with the loss averaging operator that has access to a different device than allocated for some tensor. Any idea what may be the problem?

Traceback (most recent call last):
  File "dlrm_s_caffe2.py", line 1127, in <module>
    dlrm.run(lX[j], lS_l[j], lS_i[j], lT[j])  # args.enable_profiling
  File "dlrm_s_caffe2.py", line 648, in run
    workspace.RunNet(self.model.net)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/workspace.py", line 254, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/workspace.py", line 215, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at context_gpu.h:206] error == cudaSuccess. 700 vs 0. Error at: /opt/conda/conda-bld/pytorch_1573049304260/work/caffe2/core/context_gpu.h:206: an illegal memory access was encountered
Error from operator:
input: "gpu_7/sd2" input: "gpu_7/loss_autogen_grad" output: "gpu_7/sd2_grad" name: "" type: "AveragedLossGradient" device_option { device_type: 1 device_id: 7 } is_gradient_op: trueframe #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x5b (0x7f2f2b90341b in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: <unknown function> + 0x3f09035 (0x7f2f2fc5c035 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #2: <unknown function> + 0x40364d0 (0x7f2f2fd894d0 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #3: caffe2::SimpleNet::Run() + 0x1a9 (0x7f2f2e446d39 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #4: caffe2::Workspace::RunNet(std::string const&) + 0x802 (0x7f2f2e4916b2 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #5: <unknown function> + 0x457eb (0x7f2f5a7ef7eb in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x46a1f (0x7f2f5a7f0a1f in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #7: <unknown function> + 0x95696 (0x7f2f5a83f696 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #29: __libc_start_main + 0xe7 (0x7f2f70847b97 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::Error'
  what():  [enforce fail at context_gpu.h:206] error == cudaSuccess. 700 vs 0. Error at: /opt/conda/conda-bld/pytorch_1573049304260/work/caffe2/core/context_gpu.h:206: an illegal memory access was encountered
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x5b (0x7f2f2b90341b in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: <unknown function> + 0x3f09035 (0x7f2f2fc5c035 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #2: <unknown function> + 0x3f091fa (0x7f2f2fc5c1fa in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #3: <unknown function> + 0x5ce4568 (0x7f2f31a37568 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #4: <unknown function> + 0x26f873e (0x7f2f2e44b73e in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #5: std::_Rb_tree<std::string, std::pair<std::string const, std::unique_ptr<caffe2::NetBase, std::default_delete<caffe2::NetBase> > >, std::_Select1st<std::pair<std::string const, std::unique_ptr<caffe2::NetBase, std::default_delete<caffe2::NetBase> > > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::unique_ptr<caffe2::NetBase, std::default_delete<caffe2::NetBase> > > > >::_M_erase(std::_Rb_tree_node<std::pair<std::string const, std::unique_ptr<caffe2::NetBase, std::default_delete<caffe2::NetBase> > > >*) + 0x2f9 (0x7f2f5a81a839 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #6: std::_Rb_tree<std::string, std::pair<std::string const, std::unique_ptr<caffe2::Workspace, std::default_delete<caffe2::Workspace> > >, std::_Select1st<std::pair<std::string const, std::unique_ptr<caffe2::Workspace, std::default_delete<caffe2::Workspace> > > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::unique_ptr<caffe2::Workspace, std::default_delete<caffe2::Workspace> > > > >::_M_erase(std::_Rb_tree_node<std::pair<std::string const, std::unique_ptr<caffe2::Workspace, std::default_delete<caffe2::Workspace> > > >*) + 0x149 (0x7f2f5a81cfb9 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #7: <unknown function> + 0x2f684 (0x7f2f5a7d9684 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #8: <unknown function> + 0x95696 (0x7f2f5a83f696 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #15: __libc_start_main + 0xe7 (0x7f2f70847b97 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)

**Comment by mnaumovfb** [comment]
Can you post the exact command you are running and the output of nvidia-smi command?

**Comment by berryweinst** [comment]
Yes sure.

command line:
```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python dlrm_s_caffe2.py --arch-interaction-op=cat --arch-sparse-feature-size 64 --arch-embedding-size 3000000-3000000-3000000-3000000-3000000-3000000-3000000-3000000 --arch-mlp-bot 1024-1024-1024-64 --arch-mlp-top 4096-4096-4096-4096-4096-4096-4096-1 --nepochs 50 --num-indices-per-lookup 38 --num-indices-per-lookup-fixed 1 --mini-batch-size 512 --data-size 8192 --print-time --loss-function bce --round-targets True --use-gpu
```

nvidia-smi (just before the crash):

| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:17.0 Off |                    0 |
| N/A   47C    P0    62W / 300W |   2172MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:00:18.0 Off |                    0 |
| N/A   44C    P0    64W / 300W |   2172MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:00:19.0 Off |                    0 |
| N/A   42C    P0    59W / 300W |   2172MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:00:1A.0 Off |                    0 |
| N/A   46C    P0    62W / 300W |   2172MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2...  On   | 00000000:00:1B.0 Off |                    0 |
| N/A   49C    P0    63W / 300W |   2172MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM2...  On   | 00000000:00:1C.0 Off |                    0 |
| N/A   47C    P0    66W / 300W |   2172MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-SXM2...  On   | 00000000:00:1D.0 Off |                    0 |
| N/A   43C    P0    60W / 300W |   2172MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   47C    P0    66W / 300W |   2172MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0    111523      C   -                                           2161MiB |
|    1    111523      C   -                                           2161MiB |
|    2    111523      C   -                                           2161MiB |
|    3    111523      C   -                                           2161MiB |
|    4    111523      C   -                                           2161MiB |
|    5    111523      C   -                                           2161MiB |
|    6    111523      C   -                                           2161MiB |
|    7    111523      C   -                                           2161MiB |
+-----------------------------------------------------------------------------+

**Comment by mnaumovfb** [comment]
This command runs fine in my environment: 
```
python
>>> import torch
>>> print(torch.__version__)
1.5.0.dev20200115
>>> torch.version.cuda
'10.1' [Nvidia Driver Version: 418.67]
```
  
What version of PyTorch are you using?

**Comment by berryweinst** [comment]
```
 import torch
>>> print(torch.__version__)
1.4.0
>>> torch.version.cuda
'10.1'
```

**Comment by berryweinst** [comment]
also tried to install the nightly but the same error occurs. I tried it on 3 different AWS instances with 8 V100 GPUs.

```
 import torch
>>> print(torch.__version__)
1.6.0.dev20200418+cu101
```

**Comment by mnaumovfb** [comment]
I was wondering if this was related to issue https://github.com/facebookresearch/dlrm/issues/42 

Can you try installing the pytorch version 1.5 that is working for me and re-trying it? I just want to rule out the above issue.

**Comment by berryweinst** [comment]
Thanks but same error for your version of pytorch:

```
>>> import torch
>>> torch.__version__
'1.5.0.dev20200115'
```

**Comment by mnaumovfb** [comment]
I'm puzzled, given that the same command seems to run fine for me. Please give me a bit of time to investigate it.

**Comment by mnaumovfb** [comment]
We have tried to reproduce this bug again, but the code works fine for us.

However, we have noticed that we can force a crash in the code if the usable RAM is shrunk by enough amount. How much RAM memory do you have on your system?

**Comment by mnaumovfb** [comment]
There has not been an update in this issue for a while and we could not repro it. Closing.

Please feel free to reopen if needed.
