### ISSUE TITLE
Parameter of RMC1, RMC2, RMC3

### ISSUE THREAD

**Issue by boringlee24** [facebookresearch/dlrm#74]
Hi,

What are the exact parameters for RMC1, RMC2 and RMC3? In the "The Architectural Implications of Facebook’s DNN-based Personalized Recommendation" paper, only the normalized parameters are specified, what are the exact parameters of these recommendation models?

**Comment by mnaumovfb** [comment]
Unfortunately, we can not disclose the exact parameters of RMC1, RMC2 and RMC3 models, only their relative dimensions.
