### ISSUE TITLE
day_count file for Kaggle

### ISSUE THREAD

**Issue by nzarif** [facebookresearch/dlrm#77]
Hi,

First of all thanks for the high-quality code. On line 119 of "dlrm_data_pytorch.py" you are trying to read files containing the count numbers of data points in training data but when Kaggle raw data is processed, such a file is not produced. Is there supposed to be a file for each training day? or just one file for all training days? a "train_day_count.npz" file is produced and I am assuming that contains the count number for all days. I have been replacing that line of code when working with Kaggle with "train_day_count.npz" address. Is that an okay thing to do? and If that is what we are supposed to do, maybe that needs fixing so the name of files produced after processing Kaggle data matches with that part of code?

**Comment by mnaumovfb** [comment]
There should be only one file for all days: train_day_count.npz. This file will be generated [on line 1071 in data_utils.py](https://github.com/facebookresearch/dlrm/blob/master/data_utils.py#L1071). So, I don't see why you should be replacing something in the code, but maybe I'm missing something.

**Comment by nzarif** [comment]
Got it, thanks a lot for your quick answer.
One more question: I have already trained a Kaggle model on a server and now copied it on my own system to do just inference. If I want to do inference for the first time, should I pass the address to "test.txt" file in the Kaggle dataset that I have downloaded as --raw-data-file?

**Comment by mnaumovfb** [comment]
You should pass both raw and pre-processed locations as command line parameters (see scripts in ./bench), but only the pre-processed files should be required.

**Comment by mnaumovfb** [comment]
It looks like this issue is resolved. Closing.
