### ISSUE TITLE
inference dataset prepare error

### ISSUE THREAD

**Issue by Danliran** [facebookresearch/dlrm#79]
Hi dlrm team,
there is an error when i want to inference base on kaggle dataset. please help to check this issue, thanks in advance.
command:
 python dlrm_s_pytorch.py  --raw-data-file=./input/test.txt    --data-generation=dataset --data-set=kaggle --use-gpu --nepochs 10  --inference-only --print-time  --test-mini-batch-size=128

Using 1 GPU(s)...
Reading raw data=./input/test.txt
Reading data from path=./input/test.txt
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 587, in <module>
    dp.make_criteo_data_and_loaders(args)
  File "/home/taishan/dlrm/dlrm_data_pytorch.py", line 485, in make_criteo_data_and_loaders
    args.memory_map
  File "/home/taishan/dlrm/dlrm_data_pytorch.py", line 115, in __init__
    memory_map
  File "/home/taishan/dlrm/data_utils.py", line 1066, in getCriteoAdData
    total_per_file[i],
  File "/home/taishan/dlrm/data_utils.py", line 996, in process_one_file
    X_int[i] = np.array(line[1:14], dtype=np.int32)
ValueError: invalid literal for int() with base 10: '5a9ed9b0'

**Comment by mnaumovfb** [comment]
The Criteo Kaggle DAC dataset consists of train.txt and test.txt files. However, the interface code is setup to only use the train.txt file. It pre-processes the data, breaking it into 7 days and using the first 6 days for training and the last day for testing.

The typical approach to experiment with the code is to train and save the model using `./bench/dlrm_s_criteo_kaggle.sh  --test-freq=1024 --save-model=<filename>` script and then use it for inference, with something like `./bench/dlrm_s_criteo_kaggle.sh --inference-only --load-model=<filename>`

In your command line you are passing test.txt file as raw input. This option is not supported.

**Comment by BWbwchen** [comment]
Hi, 

I come across this problem also.
I want to use the Criteo Kaggle DAC dataset's test.txt to generate the label for each line.

But It seems the existing code didn't support this feature..? or did I just miss something?

Would anyone be able to help me? Thx.

**Comment by chinmayjainnnn** [comment]
@BWbwchen Hi did you find any solution
