### ISSUE TITLE
'NpzFile' object has no attribute 'zip'

### ISSUE THREAD

**Issue by jzhang82119** [facebookresearch/dlrm#83]
I have processed the data, kaggleAdDisplayChallenge_processed.npz is generated, 
Now I am trying to follow the instruction below
"The processed file (.npz) can be used for subsequent runs with --processed-data-file=<path/.npz>"

I am not sure if I correctly understand the meaning of this step. Anyway, I run it  with --processed-data-file=./input/kaggle/kaggleAdDisplayChallenge_processed.npz and got the following error. 

python dlrm_s_pytorch.py --arch-sparse-feature-size=16 --arch-mlp-bot="13-512-256-64-16" --arch-mlp-top="512-256-1" --data-generation=dataset --data-set=kaggle --raw-data-file=./input/kaggle/train.txt --processed-data-file=./input/kaggle/kaggleAdDisplayChallenge_processed.npz --loss-function=bce --round-targets=True --learning-rate=0.1 --mini-batch-size=128 --print-freq=1024 --print-time --use-gpu | tee kaggle_pt.log
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 557, in <module>
Using 4 GPU(s)...
Reading pre-processed data=./input/kaggle/kaggleAdDisplayChallenge_processed.npz
    dp.make_criteo_data_and_loaders(args)
  File "/root/dlrm/dlrm_data_pytorch.py", line 485, in make_criteo_data_and_loaders
    args.memory_map
  File "/root/dlrm/dlrm_data_pytorch.py", line 200, in __init__
    with np.load(file) as data:
  File "/root/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 444, in load
    pickle_kwargs=pickle_kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 193, in __init__
    _zip = zipfile_factory(fid)
  File "/root/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 119, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/root/miniconda3/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/root/miniconda3/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
Exception ignored in: <function NpzFile.__del__ at 0x7efd349e3dd0>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 230, in __del__
    self.close()
  File "/root/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 221, in close
    if self.zip is not None:
AttributeError: 'NpzFile' object has no attribute 'zip'

I have no idea. Thanks for help.

**Comment by mnaumovfb** [comment]
I have not see this error before. I suspect that for some reason you have a corrupted .npz file.

The easiest way to run the code starting from raw data is to execute the following command `./bench/dlrm_s_criteo_kaggle.sh --test-freq=1024`

Please make sure you remove all previously generated intermediate files prior to running it, and just have train.txt in your `./input` directory. Let me know if it works for you.

**Comment by jzhang82119** [comment]
I followed your suggestion to execute the following command. The training works. 

./bench/dlrm_s_criteo_kaggle.sh --test-freq=1024

So seems like it is not necessary to do the data preparation as below. 

"Please do the following to prepare the dataset for use with DLRM code:
First, specify the raw data file (train.txt) as downloaded with --raw-data-file=<path/train.txt>
This is then pre-processed (categorize, concat across days...) to allow using with dlrm code
The processed data is stored as .npz file in <root_dir>/input/.npz
The processed file (.npz) can be used for subsequent runs with --processed-data-file=<path/.npz>"

I looked at the code of dlrm_s_criteo_kaggle.sh, it does not have --use-gpu parameter. Will this cause the training too slow?

**Comment by mnaumovfb** [comment]
These command line arguments are passed to the model in the `./bench/dlrm_s_criteo_kaggle.sh`, and the code will do the pre-processing automatically for you.

The shell script accepts an extra argument, so to run the model on GPU you can always write
```
export CUDA_VISIBLE_DEVICES=0
./bench/dlrm_s_criteo_kaggle.sh "--test-freq=1024 --use-gpu"
```

**Comment by mnaumovfb** [comment]
I'm assuming this is resolved. Closing.
