### ISSUE TITLE
Performance benchmarking accuracy 0.000 %

### ISSUE THREAD

**Issue by jzhang82119** [facebookresearch/dlrm#85]
I am trying to understand the following section
1.Performance benchmarking

./bench/dlrm_s_benchmark.sh

After I ran the script, it generates the following files:

-rw-r--r--  1 root root      10313 Jun  6 21:17 model1_CPU_PT_28.prof
-rw-r--r--  1 root root   74281416 Jun  6 21:17 model1_CPU_PT_28.json
-rw-r--r--  1 root root        937 Jun  6 21:17 model1_CPU_PT_28.log
-rw-r--r--  1 root root         13 Jun  6 21:24 model1_CPU_C2_28.log
-rw-r--r--  1 root root       1777 Jun  6 21:24 model1_CPU_C2_28.prof
-rw-r--r--  1 root root      12655 Jun  6 21:33 model1_GPU_PT_1.prof
-rw-r--r--  1 root root  266647110 Jun  6 21:33 model1_GPU_PT_1.json
-rw-r--r--  1 root root        922 Jun  6 21:33 model1_GPU_PT_1.log
-rw-r--r--  1 root root       1777 Jun  6 21:40 model1_GPU_C2_1.prof
-rw-r--r--  1 root root         18 Jun  6 21:40 model1_GPU_C2_1.log
-rw-r--r--  1 root root      15055 Jun  6 21:49 model1_GPU_PT_2.prof
-rw-r--r--  1 root root  516873713 Jun  6 21:50 model1_GPU_PT_2.json
-rw-r--r--  1 root root        922 Jun  6 21:50 model1_GPU_PT_2.log
-rw-r--r--  1 root root       1777 Jun  6 21:57 model1_GPU_C2_2.prof
-rw-r--r--  1 root root         18 Jun  6 21:57 model1_GPU_C2_2.log
-rw-r--r--  1 root root      15055 Jun  6 22:07 model1_GPU_PT_4.prof
-rw-r--r--  1 root root  776941443 Jun  6 22:08 model1_GPU_PT_4.json
-rw-r--r--  1 root root        922 Jun  6 22:08 model1_GPU_PT_4.log
-rw-r--r--  1 root root       1777 Jun  6 22:16 model1_GPU_C2_4.prof
-rw-r--r--  1 root root         18 Jun  6 22:16 model1_GPU_C2_4.log
-rw-r--r--  1 root root      15055 Jun  6 22:25 model1_GPU_PT_8.prof
-rw-r--r--  1 root root  777380840 Jun  6 22:27 model1_GPU_PT_8.json
-rw-r--r--  1 root root        922 Jun  6 22:27 model1_GPU_PT_8.log
-rw-r--r--  1 root root       1777 Jun  6 22:34 model1_GPU_C2_8.prof
-rw-r--r--  1 root root         18 Jun  6 22:34 model1_GPU_C2_8.log

Then I check the logs, found they are all showing accuracy 0%, is there something I missed in the script. Is this expected?

cat model1_GPU_PT_1.log
Using 1 GPU(s)...
time/loss/accuracy (if enabled):
Finished training it 100/1000 of epoch 0, 14.94 ms/it, loss 0.083371, accuracy 0.000 %
Finished training it 200/1000 of epoch 0, 14.99 ms/it, loss 0.083515, accuracy 0.000 %
Finished training it 300/1000 of epoch 0, 14.95 ms/it, loss 0.083672, accuracy 0.000 %
Finished training it 400/1000 of epoch 0, 14.93 ms/it, loss 0.082935, accuracy 0.000 %
Finished training it 500/1000 of epoch 0, 14.92 ms/it, loss 0.083580, accuracy 0.000 %
Finished training it 600/1000 of epoch 0, 14.81 ms/it, loss 0.083138, accuracy 0.000 %
Finished training it 700/1000 of epoch 0, 14.95 ms/it, loss 0.083406, accuracy 0.000 %
Finished training it 800/1000 of epoch 0, 14.85 ms/it, loss 0.083437, accuracy 0.000 %
Finished training it 900/1000 of epoch 0, 15.09 ms/it, loss 0.083266, accuracy 0.000 %
Finished training it 1000/1000 of epoch 0, 15.06 ms/it, loss 0.083328, accuracy 0.000 %

**Comment by ouwyukha** [comment]
I'm suspicious on dlrm_s_pytorch.py at line 963:
`A = np.sum((np.round(S, 0) == T).astype(np.uint8))`
As we know the T (target) should be a binary. But if we try to print T, it's actually a float, making equal comparator nearly hits impossible.

I don't know it's a bug or not, but if we changed to np.round(T, 0), all the T's become 0 because the float value is under 0.5 and the accuracy becomes 100%. I don't have powerful pc to benchmark using criterio dataset, so please don't take my words.

**Comment by mnaumovfb** [comment]
Please add the following command line argument to your execution line `--round-targets=True`. 
./bench/dlrm_s_benchmark.sh --round-targets=True

Notice that as @ouwyukha pointed out, when using synthetic setting, the targets are randomly generated floating point numbers. This fine for tracking and experimenting with the loss, but to track [accuracy](https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L963) you need them to be rounded.

Let me know if it works for you.

**Comment by jzhang82119** [comment]
Now it is better.

cat model1_GPU_PT_1.log
Using 1 GPU(s)...
time/loss/accuracy (if enabled):
Finished training it 100/1000 of epoch 0, 14.88 ms/it, loss 0.250200, accuracy 49.955 %
Finished training it 200/1000 of epoch 0, 14.65 ms/it, loss 0.250053, accuracy 49.842 %
Finished training it 300/1000 of epoch 0, 14.64 ms/it, loss 0.250048, accuracy 49.895 %
Finished training it 400/1000 of epoch 0, 15.46 ms/it, loss 0.250032, accuracy 50.014 %
Finished training it 500/1000 of epoch 0, 16.24 ms/it, loss 0.250027, accuracy 50.082 %
Finished training it 600/1000 of epoch 0, 15.97 ms/it, loss 0.250037, accuracy 50.023 %
Finished training it 700/1000 of epoch 0, 16.21 ms/it, loss 0.250046, accuracy 50.025 %
Finished training it 800/1000 of epoch 0, 16.22 ms/it, loss 0.250046, accuracy 49.918 %
Finished training it 900/1000 of epoch 0, 16.30 ms/it, loss 0.250039, accuracy 49.839 %
Finished training it 1000/1000 of epoch 0, 16.29 ms/it, loss 0.250028, accuracy 50.060 %

**Comment by mnaumovfb** [comment]
I'm assuming this is resolved. Closing.
