### ISSUE TITLE
random and synthetic datasets 0.0% accuracy

### ISSUE THREAD

**Issue by pintonos** [facebookresearch/dlrm#88]
Hi there!
Since my computer is not able to run the Criteo Dataset i wanted to use a smaller random generated or synthetic dataset. 
However, accuracy while training is always 0.000%. Is this wanted or is there a trick to change this?
Using the `--test-freq` parameter also does not to anything, while running the code.

This is my used execution line:
`python .\dlrm_s_pytorch.py --data-generation=synthetic --data-size=100 --test-freq=10`

**Comment by mnaumovfb** [comment]
Please add the following command line argument to your execution line `--round-targets=True`. Let me know if it works for you.

Notice that when using synthetic setting, the targets are randomly generated floating point numbers. This fine for tracking and experimenting with the loss, but to track [accuracy](https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L963) you need them to be rounded.
