### ISSUE TITLE
Caffe2 profiling

### ISSUE THREAD

**Issue by TMVector** [facebookresearch/dlrm#9]
I have installed dependencies through Anaconda, apart from pytorch/caffe2, which I installed from source at SHA f2623c74a9e76dd3aa5dcdd5aaeb63d12db52587 to match the stipulation of pytorch-nightly 06-10-2019. I also tried some of the latest point releases of pytorch/caffe2.

Running `./bench/dlrm_s_benchmark.sh`, the PyTorch output is fine, but the only text in the caffe2 output is an error message:
```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
ERROR: unknown command line flag 'caffe2_logging_print_net_summary'
```

**Comment by mnaumovfb** [comment]
The script will try to run the code on both CPU and GPU by default. It seems that your machine does not have a GPU. Therefore, please change line 17 in dlrm_s_benchmark.sh script from
gpu=1
to
gpu=0

Let me know if this works.

**Comment by TMVector** [comment]
I forgot to mention that it's the CPU output which has this problem. I am aiming to reproduce https://arxiv.org/pdf/1906.03109.pdf. My changes are visible on this branch: https://github.com/TMVector/dlrm/tree/benchmark-paper

Thanks for the prompt response.

**Comment by mnaumovfb** [comment]
Hmmm, I suspect this is somehow related to the pytorch/caffe2 version you have installed.

As a workaround I would try to disable profiling using either of the following two things:
1. Comment line 58 "--enable profiling" in dlrm_s_benchmark.sh script
2. Comment line 473 "--caffe2_logging_print_net_summary=1" in dlrm_s_caffe2.py

**Comment by TMVector** [comment]
Can you confirm what version of pytorch/caffe2 you are using? The README says "pytorch-nightly (6/10/19)" -- is that also where your caffe2 comes from?

**Comment by mnaumovfb** [comment]
The version in the README is correct. I have rerun the code and I can not reproduce this issue at the moment. Please try the workarounds on your end and let me know if they work.

ps. Also, I wanted to point out that the code is build using standard PyTorch/Caffe2 operators and it should work with any versions of the frameworks. The only function that was perhaps not available in earlier versions is torch.tril_indices, which generates a set of lower triangular indices.

**Comment by TMVector** [comment]
I can run the script with the "--caffe2_logging_print_net_summary=1" line commented out, but I don't get per-operator profiling like I do with PyTorch.
The time per iteration is higher for caffe2 than for pytorch though, so I think it's okay to focus on PyTorch for now.

Thanks for your help :)

**Comment by mnaumovfb** [comment]
Sounds good. Good luck with your work.
