### ISSUE TITLE
Minor issues about visualize.py

### ISSUE THREAD

**Issue by huwan** [facebookresearch/dlrm#92]
A sample run of the code is given in `visualize.py`. But several errors occur when trying to run the following command:
https://github.com/facebookresearch/dlrm/blob/91b28f1644bc492d1854d119a996806015d55300/tools/visualize.py#L18

1. "ModuleNotFoundError: No module named 'dlrm_data_pytorch' "
I found the answer from https://stackoverflow.com/a/60264029/. It says we should set PYTHONPATH environment variable in root project directory, using `export PYTHONPATH=.`.

2. "visualize.py: error: unrecognized arguments: –dataset=kaggle"
It seems that "–" in the given command line should be changed to "--", i.e., `--dataset=kaggle`.

**Comment by mnaumovfb** [comment]
1. Thank you for pointing it out and providing a solution. 
2. I have fixed this typo.

**Comment by huwan** [comment]
Thank you, closing the issue.
